### ISSUE TITLE
[FO] fn:filter with a function returning empty sequence

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#10]
filter has signature:

    fn:filter($seq as item()*, $f as function(item()) as xs:boolean) as item()*

It could easily be changed to:

    fn:filter($seq as item()*, $f as function(item()) as xs:boolean?) as item()*

with `()` meaning `false()`.

Then it could be used with a map to pick elements from the seq. E.g.

    filter(1 to 10, map {3: true(), 4: true()}) 
   ~> (3, 4)
   
    filter(("a", "b", "b", "c", "d"), map {"b": true(), "d": true()}) 
   ~> ("b", "b", "d")
   
Same for array:filter

**Comment by ChristianGruen** [comment]
Good idea.

**Comment by ChristianGruen** [comment]
I assume there was a reason not to compute the EBV for the function results? Could this be a possible generalization for 4.0, or could the reasoning be added to the spec?

**Comment by michaelhkay** [comment]
I'm in favour of using EBV for predicate functions. Particularly with the abbreviated notation for inline functions. People think of `self::x` as a boolean expression because it's widely used as such, and it seems very unnatural to have to write `boolean(self::x)` or `exists(self::x)`. Unfortunately theres a compatibility problem with changing it, though: if your predicate function is `function($x as node()) as xs:boolean {$x/@married}` then it currently atomizes the attribute node and returns it's typed value, which might not be the same as its EBV.

**Comment by ChristianGruen** [comment]
Oh, I see. Thanks. If it’s no big deal, it could help to add a little clarification in the spec.

**Comment by michaelhkay** [comment]
The spec for fn:filter does emphasize more than once that the function must return an xs:boolean, it doesn't take the EBV. I think we should therefore close this with no action.
