### ISSUE TITLE
How to invert a predicate function

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1007]
It's nice to be able to write

`index-where($in, contains(?, 'e'))`

to select all the items that contain an 'e'. 

What should we write in order to select all the items that do not contain an 'e'? All formulations seem a bit clumsy in comparison:

`index-where($in, fn{not(contains(., 'e'))})`
`index-where($in, chain((contains(?, 'e'), not#1))`

Perhaps this is a sufficiently common requirement that it would be helpful to allow

`index-where($in, inverse(contains(?, 'e')))`

where `inverse($predicate)` is defined as `fn($it, $pos){not($predicate($it, $pos))}`

**Comment by ChristianGruen** [comment]
I see many other use cases for a real function composition, so I would be happy if we could find a solution for that (as you’ve already motivated in #882).

My current favorite would still be a basic `fn:compose` function (i.e., chaining without application). Mark’s second suggestion was to introduce a custom operator. If we do that, I think we should choose keywords, no symbols.

A summary of the suggestions in the other issue (and variations):

#### Right-to-left Composition

```xquery
index-where( $in, compose(not(?), contains(?, 'e')) )
index-where( $in, compose( (not(?), contains(?, 'e')) ) )
index-where( $in, not(?) after contains(?, 'e') )
```

#### Left-to-right Composition

```xquery
index-where( $in, compose( (contains(?, 'e'), not(?)) ) )
index-where( $in, compose(contains(?, 'e'), not(?)) )
index-where( $in, chain( (not(?), contains(?, 'e') ) )
index-where( $in, contains(?, 'e') then not(?) )
index-where( $in, contains(?, 'e') before not(?) )
index-where( $in, contains(?, 'e') and-then not(?) )
index-where( $in, contains(?, 'e') .> not(?) )
```

I haven’t checked if all proposals are grammatically unambiguous.

**Comment by ChristianGruen** [comment]
Some user feedback I got today on this topic (roughly reproduced and adopted to the example above):

> `index-where($input, fn($s) { not(contains($s, 'e')) })` is compact enough; please don’t make it any more cryptic.

**Comment by apb2006** [comment]
I find myself often "not" ing expressions. It is a common operation. It is adding the parenthesis that takes me the time. 
Is there any mileage in borrowing from the APL solution https://aplwiki.com/wiki/Not? (I see there is no tilde ~ in the XQuery spec).
Something like `~ expr` meaning convert `expr` to boolean value or boolean sequence then logically invert? Not cryptic at all I think

**Comment by MarkNicholls** [comment]
I almost posted a similar suggestion the other day, but wondered if it was better on stack overflow as I think it would show my ignorance of the language rather than be a genuine suggestion.

this

`index-where($in, contains(?, 'e'))`

i like very much

can I unpack what it does a bit....so....any expression containing the ? is mapped to

`index-where($in, fn($x) { contains($x, 'e')})
`
yes?
(actually knowing where to put the fn is quite fiddly)

so

`index-where($in, fn($x) { contains($x, 'e')})
`
 
maps to

`index-where($in, not(fn($x) { contains($x, 'e'))})
`
?

(which isnt "right")
(I like '?' slightly less now..not because its badly designed just the problem it solves seems a bit wrinkly)

but

so if we had compose you would write

`index-where($in, contains(?, 'e') >> not)`

or

`index-where($in, not << contains(?, 'e'))`

(thats the F#/Xpath mash up, but I get why people struggle with cryptic operators, it all gets a bit point free and your code disolves into combinators)

**Comment by ChristianGruen** [comment]
> I find myself often "not" ing expressions. It is a common operation. It is adding the parenthesis that takes me the time. 
Is there any mileage in borrowing from the APL solution https://aplwiki.com/wiki/Not? (I see there is no tilde ~ in the XQuery spec).

@apb2006 Yes, this syntax would have a certain appeal. There is at least one proposal to introduce `~` as a value mapping operator (#755), but there hasn’t been much enthusiasm for it so far, and it’s just one of the presented alternatives.

In principle, `~E` could be used to invert both atomic items and functions:

* `~FUNCTION` would be a shortcut for `fn(ARGS) { not(FUNCTION(ARGS)) }`
* `~OTHER-TYPE` would be equivalent to `not(OTHER-TYPE)`

For example, …

```xquery
for $e in ('abc', contains(?, 'e'))
return ~$e
```

…would result in:

```xquery
not('abc'),
fn($arg1) { not(contains($arg1, 'e')) }
```

The challenges I see are that the decision cannot always be taken at compile time. Next, the type-based decision could get in the way of my hope to extend EBVs to more types (#829).

@MarkNicholls 

> `index-where($in, not(contains(?, 'e'))) `
> maps to
> `index-where($in, not(fn($x) { contains($x, 'e'))}) ` ?

As `not(...)` is a static function call, I assume it would need to be…

```xquery
index-where($in, fn($arg1) { not(contains($arg1, 'e')) })`
```

Similarly, this would mean that `fn:not` would need to treat function item arguments differently than other types. Since `fn:not` is a fairly fundamental operation, the consequences might be a bit too extensive.

> `index-where($in, contains(?, 'e') >> not)`
> or
> `index-where($in, not << contains(?, 'e'))`

It would probably need to be `not#1` or `not(?)`. Otherwise, `not` would be interpreted as element name:

```xquery
<x><not></x> ! not → <not>
```

> P.S. my aborted suggestion was to make lambdas more terse so something like
> `$x -> not(contains($x),'e') `

A year ago, there was a lot of discussion in this repo on how a more compact syntax for function items like `function($a) { $a }` could look like. We decided to…

* Introduce `fn` as an alias for `function`: `fn($a) { $a }`.
* Next, focus functions were introduced, which bind single arguments to the context: `fn { . }`
* We decided against the `$a -> ...` syntax, as it’s more difficult to parse, and as it would introduce ambiguities when specifying types (`$a as xs:int ->` could either mean `function($a as xs:int))` or `function($a) as xs:int)`).

**Comment by dnovatchev** [comment]
> What should we write in order to select all the items that do not contain an 'e'? All formulations seem a bit clumsy in comparison:
> 
> `index-where($in, fn{not(contains(., 'e'))})` `index-where($in, chain((contains(?, 'e'), not#1))`
> 
> Perhaps this is a sufficiently common requirement that it would be helpful to allow
> 
> `index-where($in, inverse(contains(?, 'e')))`
> 
> where `inverse($predicate)` is defined as `fn($it, $pos){not($predicate($it, $pos))}`

How can one decide that:

**(1) &nbsp;&nbsp;&nbsp;`index-where($in, inverse(contains(?, 'e')))`**

is more convenient (shorter, easier to understand) than just:

**(2)&nbsp;&nbsp;&nbsp;`index-where($in, not(contains(?, 'e')))`**

The opposite is actually obvious - (2) is both shorter and easier to understand, because it doesn't require the reader to learn a new function.

Isn't the proposed **`inverse`** equivalent to **`not`** ?

OK, it is not - it is the **_lifted_** `not`

We could define a **_lifting operator_** - probably the topic for a separate issue. Lifting can also easily be accomplished using a [**_decorator_**](https://github.com/qt4cg/qtspecs/issues/106).

**Comment by dnovatchev** [comment]
@ChristianGruen 

> index-where( $in, chain( (not(?), contains(?, 'e') ) )

This is not what we want.

We want:

`index-where( $in, chain( ( contains(?, 'e'), not(?) ) )`

I agree with the provided user feedback:

> index-where($input, fn($s) { not(contains($s, 'e')) }) is compact enough; please don’t make it any more cryptic.

**Comment by ChristianGruen** [comment]
> If we want to use `chain` here (I wouldn't ...), then it needs to be written as:
> 
> `index-where( $in, chain( ( contains(?, 'e'), not(?) ) )`

Thanks, Dimitre, I’ve corrected this.

**Comment by MarkNicholls** [comment]
so actually even though I think its a dead end, @dnovatchev observation about lifting is interesting because it generalises the issue 
(I did look up python decorators, even though i write in python, very reluctantly, but I think the fp treatment of lift is clearer)

(apologies for the pigeon XPath)

so the way to write this directly

`index-where($in, inverse(contains(?, 'e')))
`
so in terms of 'lift' is this

`index-where($in, lift(not(?),(contains(?, 'e'))))
`
ew...I personally dont want to do this, but its interesting.

because it generalises to "or" and "and"

lets say we want to test if it contains 'e' and 'f' we can go

`index-where(
   $in, 
   lift2(
      fun($x,$y) { or($x,$y) },
      contains(?, 'e')
      contains(?, 'f'))
`

("or" doesnt exist as a function so I've taken liberties)

ok, thats pretty horrid, but lets say we decide that this is common enough to write functions to capture boolean operators.

sorry...I have to go to F# or haskell now...because there's only so much pigeon syntax before it loses all meaning.

so in F#

consider the predicate (I've put the signatures in to hopefully help the comprehension)

```
let isEvenAndNotDiv3 : int -> bool = 
    fun x -> (isEven x) && (not(isMult3 x))

```
so basically a function that tests if something is even and not a multiple of 3
isEven and isMult3 are my predicates, && and not are F# functions

so we can lift our function functor like this (in haskell this is out the box, in F# ive writen the function functor)

```
// lift or into function functor
let (|||) f g = lift2 (||) f g
// lift and
let (&&&) f g = lift2 (&&) f g
// lift not
let fnot f = lift not f
```

and then write

`let isEvenAndNotDiv3_2 = isEven &&& (fnot isMult3)
`

would i ever do this?

absolutely not...I suspect people who write point free all the time find this easy, I dont, I can only read pointfree code if it compiles, as soon as it doesnt I have to put the parameter back in.

so for me this is an interesting dead end, function composition (i.e. "lift") is useful for 'not' and I think has value in the language as a first class pointfree operator of some sort, not using the language of lifting.

general lifting (i.e. lift2, lift3) is too much for me in xpath...though i note that Paul Hudak did once say something like, he never got functional programming until he suddenly understood lifting.

@dnovatchev 

I'd be interested as an probably pointless academic exercise how you would apply python decorators to the above more general context.

(I don't like python, and I didn't warm to decorators, they seem a convoluted mechanism to do something simple, but do you think it would be elegant? or a mess?)

**Comment by dnovatchev** [comment]
> @dnovatchev
> 
> I'd be interested as an probably pointless academic exercise how you would apply python decorators to the above more general context.
> 
> (I don't like python, and I didn't warm to decorators, they seem a convoluted mechanism to do something simple, but do you think it would be elegant? or a mess?)

@MarkNicholls ,

Yes, with or even without decorators this still very much a mess,

I enjoyed looking at your proposed expression that uses lifting-operators:

> `let isEvenAndNotDiv3_2 = isEven &&& (fnot isMult3)`

It looks elegant, but once you need to provide the actual arguments for the expression, then it becomes really messy.

- How to provide the arguments' values?
 
- Where to provide the argument values - at the rightmost end (in how many (nested?) pairs of brackets)? Or at the leftmost? Or interspersed within the expression?
 
- In what order?
 
- How to name the arguments so it is obvious at a glance which argument's values are consumed by which of the lifted functions?

This is rather challenging even to think of, not even to speak about design, and seems the resulting language would be very difficult to comprehend - due to all these complexities.

**Comment by MarkNicholls** [comment]
@dnovatchev 

rarely for me that code is actually real working code

`isEvenAndNotDiv3 7`

does evaluate to false

So we can, quite "correctly' introduce &&& and ||| and fnot into the language and use it to compose predicates and "remove the boilerplate" of parameters and fn and parenthesis, including MKats original one, and all logical predicates (in a single var) made from and/or/not.

Would anyone use it?...I suspect not...I wouldn't.

So I'd stop at function composition until 'normal' programmers (including me) are more comfortable with point free code (which is possibly never), but it does give you a general formulation of the issue in which to discuss it.

**Comment by dnovatchev** [comment]
> @dnovatchev
> 
> rarely for me that code is actually real working code
> 
> `isEvenAndNotDiv3 7`
> 
> does evaluate to false

@MarkNicholls 

Yes, the above is a rare case.

I was talking about having to lift more than one function in an expression, and most of these functions have to be lifted on subset of their arguments.

Also, imagine "nested lifting" .

**Comment by MarkNicholls** [comment]
@dnovatchev 

sorry I don't understand 

this is lifting more than 1 function, its referentially transparent so..so the substitutions work backwards too (i.e. "equational reasoning" or whatever its called)
,
```
isEvenAndNotDiv3 7
(isEven &&& (fnot isMult3)) 7
(lift2 (&&) isEven ((lift not) isMult3)) 7
```

theres 2 lifts here, one "nested", but you can have 100 lifts and nesting where you like, your just working in the "functor" space not the value space.

The theory works for n parameters e.g. `lift2` is lifting a function in 2 params, but ultimately the result here is a function in 1 param, because that's what predicates are, but if you want one in 10 params then thats fine just use Lift10....(but i'd use "applicative functors" at that point).

**Comment by dnovatchev** [comment]
@MarkNicholls 

What I mean (roughly) is that in the common case where the expression contains many calls (some of them nested) to lift functions with different arity (not just the arity of one), then the complexity (inverse to readability and understandability) rises maybe as **`O(N^m)`** where **`m`** is the maximum nestedness of lifting.

I think it would be easy to construct very unwieldy expressions, leaving this as an exercise to the reader.

In your particular case you have only one input argument and a very modest lifting nestedness (2), and a very short expression.

What if the expression contains many lifts and the arguments for all these lifted functions must be provided after the expression? How does one know which argument is for which expression, and the required order and grouping of the arguments?

And even if there are well-established rules for specifying this, such expressions would generally be extremely challenging to read and understand.

**Comment by MarkNicholls** [comment]
the example I've given shows these 2 expressions

`fun x -> (isEven x) && (not(isMult3 x))
`
and

`          isEven &&& (fnot isMult3)
`

their similarity is not coincidental, but purely mechanical, I wrote the 2nd one mechanically, and this can be recursively applied to arbirtrary complexity (I think).

The set of operators is closed, the lifts are hidden behind operators on the predicate functions that map 1:1 to boolean operators, I think there isnt an explosion of complexity, you just have to "believe" the trick.

I think the problem is more than if you need to map the input to the predicate (quite common in xpath) then you have a problem, because the parameter doesnt 'exist' inside the expression.

lets make this real, unfortunately in F# (sorry)

(this isnt how you would write it, its correct but very clumsy, but I have to try to write it in an XPath predicate style, I don't want to introduce types, so for the moment I'll use a tuple as a simple example of non atomic data)

```
let xs = 
    List.filter 
        (fun xy -> isEven (fst xy) && (not (isMult3 (fst xy + snd xy) )))
        [ (1,2); (3,6); (8,0) ; (7,1) ]

```

fst takes the 1st element of a tuple, snd takes the second (so consider then analogous to simple xpath attribute or element expressions), so this filters the list by saying the 1st value is even and the sum isnt divisible by 3.

Now I struggle to see how to map that into the functor space I have created above very easily.

if i had to do it I'd do something like this...you need to make all the functions operator ultimately on the passed parameter, so we use a bit of function composition and introduct a lambda to do the addtion

```
let ys = 
    List.filter 
        (fun xy -> ((isEven << fst) xy) && (not ((isMult3 << (fun xy' -> fst xy' + snd xy')) xy)))
        [ (1,2); (3,6); (8,0) ; (7,1) ]

```

now we can apply the mechanical rules and now use the lifted operators (<< is function composition).

```
let zs = 
    List.filter 
        ((isEven << fst) &&& (fnot (isMult3 << (fun xy' -> fst xy' + snd xy'))))
        [ (1,2); (3,6); (8,0) ; (7,1) ]

```

ok, it works....but what a car crash, with a nasty mangled lambda in it....

ok, so now lets squash the lambda

```
let bs = 
    List.filter 
        ((isEven << fst) &&& (fnot (isMult3 << (lift2 (+) fst snd))))
        [ (1,2); (3,6); (8,0) ; (7,1) ]

```

ok, that made my head REALLY hurt...and in a way its a disaster because now the programmer needs to know how to lift, its leaked out of our boolean abstraction.

now its leaked out well then my lifting can be over arbritrary numbers of parameters so I probably need to up the stakes to applicative functors....another raft of mind boggling symbols.

something like (this is a guess)

```
let bs = 
    List.filter 
        ((isEven << fst) &&& (fnot (isMult3 << ((+) <!> fst <*> snd))))
        [ (1,2); (3,6); (8,0) ; (7,1) ]

```
 
and now XPath has turned into Haskell just to handle slightly verbose predicates....no thanks (I love Haskell but also hate it, because it proves to me I'm not clever enough to program in it).

the end.

lets just add function composition, compose "not" and forget the rest of it.

**Comment by dnovatchev** [comment]
@MarkNicholls 
This was a good illustration of what I wanted to say. Thank you!

A compiler is not a human being and is not able to complain about any complex or messy input - thus we may abuse it beyond any limits.

But if we are to read, remember and understand what we wrote once upon a time... then we need to keep it simple.

The KISS principle.

I have been taught that the purpose of writing is to enhance communication and preserve valuable artifacts. Stepping beyond this definition would be unwise and counterproductive.

**Comment by ndw** [comment]
The CG decided to close this issue without further action at [meeting 067](https://qt4cg.org/meeting/minutes/2024/02-27.html).
