### ISSUE TITLE
fn:serialize line breaks

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#101]
Normally fn:serialize uses LF for line breaks

But on Windows you want to have CR LF

There could be an option for that

**Comment by yamahito** [comment]
Can't you already do this with `use-character-maps`?

**Comment by benibela** [comment]
I did not think of that

But it is unclear how that interacts with indentation. Indentation is applied after the character map, so it would have no effect on it at all. Then you would get mixed line endings. Although the actual indentation is implementation defined, so perhaps there are implementation checking for map.

**Comment by michaelhkay** [comment]
I think there is a case for a serialization parameter `line-ending="string"`, to be used (a) to substitute any 0x0A character that appears in a text/attribute/comment etc node being serialised, and (b) to be used when indenting. The string would have to be one of the line ending sequences recognised by an XML 1.0 or 1.1 parser for the purpose of line ending normalisation.

**Comment by michaelhkay** [comment]
I propose that we introduce a new serialisation parameter `line-ending`. The value is (logically) one of the sequences that an XML parser treats as equivalent to xA when performing line ending normalisation, that is one of x0A, x0D, x0Dx0A, x0Dx85, x85, or x2028. In the serialization parameter, the value is written in the form (x0*A|x0*85|x0*D(x0*A|x0*85)?|x0*85|x0*2028), with upper and lower case letters interchangeable. The default is "unspecified", and the default value may be selected by setting the parameter to the zero-length string.

The parameter has two effects:

(a) Unless there is already a character map that defines a mapping for the character xA, a value other than "unspecified" has the effect of adding a mapping for the character xA to the character map.

(b) When indent="yes" is specified, a value other than "unspecified" indicates that whenever the (implementation-defined) indentation algorithm generates a new line, it should use the selected line ending character sequence.

Note: the value "unspecified" differs from the value "xA", because in the first case the indentation algorithm can choose any newline representation it wants (for example, it can use the operating system default).

**Comment by ChristianGruen** [comment]
As XPath supports regular expressions, and now that we have `fn:char` (see #121/#261), we should additionally allow `\r`, `\r\n` and `\n` as newline character values.

**Comment by ChristianGruen** [comment]
Related (end-of-line handling when parsing text): #216

**Comment by ChristianGruen** [comment]
> I think there is a case for a serialization parameter `line-ending="string"`, to be used (a) to substitute any 0x0A character that appears in a text/attribute/comment etc node being serialised, and (b) to be used when indenting. The string would have to be one of the line ending sequences recognised by an XML 1.0 or 1.1 parser for the purpose of line ending normalisation.

I assume that `line-ending` should also affect the `item-separator` string.
In addition to `\n`, it should be applied to `\r\n` and `\r` (which means that a single lookup will be required).

**Comment by ChristianGruen** [comment]
Closed in favor of #1234.
