### ISSUE TITLE
XQuery: Normalize line endings

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1101]
Various tests, such as [`line-ending-Q002`](https://github.com/qt4cg/qt4tests/blob/c4210d9d22e756a05dfb54a0ca06fae159fe0bbc/misc/XMLEdition.xml#L132-L140), validate if line ending are normalized when parsing the input:

```xml
<test-case name="line-ending-Q002">
  <description>Normalization of line endings in XQuery</description>
  <created by="Michael Kay" on="2011-11-24"/>
  <dependency type="spec" value="XQ10+"/>
  <test>deep-equal(string-to-codepoints('&#xd;&#xa;'), (10))</test>
  <result>
    <assert-true/>
  </result>
</test-case>
```

I cannot find a corresponding note in the current [XQuery 4 draft](https://qt4cg.org/specifications/xquery-40/xquery-40.html). Should we add it?

I would welcome this normalization. I assume that no one over the last decades has missed carriage return in XML?

**Comment by michaelhkay** [comment]
Interesting.

XQuery 1.0 stated that line endings were normalized (as per XML) in string literals and in element content constructors (which is the only place it matters, because everywhere else all whitespace is treated uniformly).

That got dropped in XQuery 3.0, and I don't know why. There's no mention of it in the changes appendix, despite the fact that it's actually a backwards incompatibility.

I can't right now find the Saxon code that does the line ending normalization, though it must be there somewhere!

The fact that the spec changed and no-one noticed seems rather remarkable.

**Comment by michaelhkay** [comment]
Some detective work: At https://github.com/w3c/qtspecs/blob/master/specifications/xquery-30/src/changes.txt are the XQuery 3.0 editor's notes regarding changes that needed to be applied to the text. Here we see:

> ACTION A-493-09: Jonathan will change XPath specification so that line-end normalization is host language defined to resolve bug 14917. Errata against 2.0.

Bug 14917 is here:

https://www.w3.org/Bugs/Public/show_bug.cgi?id=14917

This led me to A3.4 in the current text which says:

Prior to parsing, the XQuery 4.0 processor must normalize all line breaks. The rules for line breaking follow the rules of [[XML 1.0]] or [[XML 1.1]]. It is implementation-defined which version is used.

**Comment by ChristianGruen** [comment]
Perfect  And sorry for the waste of your time; I’ll remember “line breaks” as a synonym for “line endings”.
