### ISSUE TITLE
Definition of focus functions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1135]
§5.4.2.6 states

> The expression function { EXPR } (or fn { EXPR }) is a syntactic shorthand for the expression function($Z as item()*) as item()* { $Z ! (EXPR) }, where $Z is a variable name that is otherwise unused. Note that the function body (EXPR) is evaluated with a [fixed focus]: the context position and context size will always be 1 (one).

This is no longer true now since generalization of the context item to context value. EXPR is evaluated once with the entire sequence $Z as the context value, it is not evaluated once for each item in $Z.

We have no direct way of expressing this in the absence of a resolution to issue #755.

**Comment by MarkNicholls** [comment]
I've read some of this....(tangent warning...again feel free to skip this, I may be revisiting a torturous conversation)

it strikes me that 

'!' and '/' are very similar, but its not obvious to me, why there are two operators, but seem to be (in FP terms) a functor map over a sequence.

(its another wrinkle where i guess), and that seems to be what #755  is about.

Its horribly difficult to find either of these operators in the 3.1 spec, apologies.

**Comment by MarkNicholls** [comment]
I assume ! preserves the order of the sequence?

removing duplicates is a bit tricky, I'm trying to think of use cases this would break if it was turned off? (I'm sure it would...in a horrid subtle way).

**Comment by ChristianGruen** [comment]
The following queries demonstrate the different behavior of `/` and `!`:

```xquery
(: document order :)
reverse(<xml><a/><b/></xml>/*) / .
reverse(<xml><a/><b/></xml>/*) ! .

(: duplicate removal :)
<xml><a/><b/></xml>/* / ..
<xml><a/><b/></xml>/* ! ..
```

…but in fact there’s no need to understand `/` in detail if you want to understand this issue and #755.

> 755 is about having an (sort of) 'apply' function that works in the same way as '!' and '/', but applies the 'function' to the 'whole' context

Right. With `~`, we would get the following equivalencies:

Name | FLWOR Expression | Operator
--- | --- | ---
Existing item map operator | `for $item in $seq return $item` | `$seq ! .`
New value map operator | `let $item := $seq return $item` | `$seq ~ `

**Comment by michaelhkay** [comment]
>I'm trying to think of use cases this would break if it was turned off?

I seem to remember convincing some of the XQuery folks of the importance of preserving document order with an example that showed an XPath 1.0 expression that output "Do not turn on the gas. It is dangerous", which under a proposal to change the semantics of "/" would have changed the output to "Do turn on the gas. It is not dangerous". I forget how I constructed the example, but it convinced people that the change was not a good idea.

**Comment by MarkNicholls** [comment]
yes sorry, I thought i was going to make a contribution, but then I realised I was barking up the wrong tree

**Comment by MarkNicholls** [comment]
in an attempt to actually say something constructive....I've read the various proposals, and it strikes me (in a blue sky way) that, to state the obvious, the issue stems from the auto flattening of sequences, rather than some lack of expressiveness in contexts.

i.e.

because

`((a,b)) = (a,b)
`
so if you go

`((a,b)) ! count(.)`

you get 

`(1,1)
`

not the 'intuitive'

`(2)`

fiddling with the context seems like a massive can of worms, and yet another subtle wrinkle that will catch me out 10 times a year, a smaller can would be to deal with the auto flattening, and allow non auto flattening sequences e.g. (to throw some random syntax at it), lets add an '|'.

so 

`(|a,b,c, (d,e),f|)`

allows us to embed the sequence `(d,e)` inside another sequence.

(this trick seems quite common, i.e. I am often forced to wrap a sequence in an element or a map or an array in order to thwart auto flattening, I also find myself doing similar things in other languages that don't support let bindings in for loops)

so


`(|(1,1)|) ! count(.) 
`
gives 2.

ok....yet another concept, but this introduction seems instinctively more transparent than modifying hows contexts work and `(||)` is a more pimitive construct than `()`.

or does this miss the point?

(I still don't like it, but it seems preferable).

**Comment by ChristianGruen** [comment]
> in an attempt to actually say something constructive....I've read the various proposals, and it strikes me (in a blue sky way) that, to state the obvious, the issue stems from the auto flattening of sequences, rather than some lack of expressiveness in contexts.

@MarkNicholls I suggest that your proposal be placed in a separate issue since it has no direct relationship to the original topic of this one. As an aside, you can currently use arrays for structured data:

```xquery
[a, b] ! array:size(.)
```

**Comment by MarkNicholls** [comment]
> We have no direct way of expressing this in the absence of a resolution to issue https://github.com/qt4cg/qtspecs/issues/755.

doesnt it evaporate the issue?

**Comment by ChristianGruen** [comment]
> doesnt it evaporate the issue?

I couldn’t see how. The definition of §5.4.2.6 needs to be edited, whatever solution we choose.

**Comment by MarkNicholls** [comment]
my comment should probably be under 755, but

isnt this the issue?

> Note that the function body (EXPR) is evaluated with a [fixed focus]: the context position and context size will always be 1 (one).

the context size is still 1, the change is to allow the context sequence to be of size 1 AND contain a sequence?

**Comment by ChristianGruen** [comment]
> the context size is still 1, the use of (||) would allow the context sequence to be of size 1 AND contain a sequence?

The idea of the focus function is that `fn($x) { $x }` and `fn { . }` will be equivalent, no matter what `$x` is and no matter how many items `$x` contains. How would the proposed syntax be able to solve that?

**Comment by michaelhkay** [comment]
>allow non auto flattening sequences

Isn't that precisely what we did when we introduced arrays?

**Comment by MarkNicholls** [comment]
ignore me

**Comment by ChristianGruen** [comment]
As motivated in https://github.com/qt4cg/qtspecs/issues/755#issuecomment-1961117678:

Could we rename Focus Function to Context Function? This seems more intuitive to me, as “context item” and now “context value”) is widely used.
