### ISSUE TITLE
format-number arguments

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1138]
Given the availability of choice item types, I propose that we merge the `format` and `format-name` parameters of `fn:format-number` into a single parameter of type `(xs:string | xs:QName | map(*))`. This seems a better design when parameters are mutually exclusive and perform a related role.

**Comment by ChristianGruen** [comment]
> This seems a better design when parameters are mutually exclusive and perform a related role.

The parameters are not mutually exclusive; see the current rules and examples…

2. The decimal format in the static context is chosen whose name matches `$format-name` if supplied, or the unnamed decimal format in the static context otherwise.
3. If `$format` is present and non-empty, the entries of this map are used to modify the decimal format chosen in the previous step. The supported keys and value types are defined in [4.7.1 Defining a decimal format](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#defining-decimal-format).

```xquery
format-number(12345, '0,###^0', 'de', {
  'exponent-separator': '^'
})
```

…but we could include the name of the decimal format as options key:


```xquery
format-number(12345, '0,###^0', {
  'name': 'de',
  'exponent-separator': '^'
})
```

This would possibly go hand in hand with suggestion 2 in #1065 to generalize the last parameter to an options parameter. It would e.g. allow us to specify the decimal-format name of the picture and the output:

```xquery
(: yields 1,234.5 :)
for $ln in ('de', 'en', 'fr', 'it', 'es')
return format-number(12345, '#,##0.#', { 'picture': 'en', 'name': $ln })
```
