### ISSUE TITLE
Iterating maps: Positional access

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1172]
With the new filter expression for maps, the context position is available. To be consistent, if we want to provide positional access for unordered data, we should…

* either provide this for map functions  as well (`map:filter`, `map:for-each`), or
* don’t provide it for map predicates at all.

**Comment by michaelhkay** [comment]
The reason for providing position for filter expressions was simply for consistency, it's simpler to define the value of position() than to say that it is undefined, because it would be the only case where a context item/value is defined and context position is not.

Filters on the unordered attribute and namespace axes support use of `position()` for the same reason.

I don't think there's a similar argument for functions such as map:filter and map:for-each.

**Comment by ChristianGruen** [comment]
> I don't think there's a similar argument for functions such as map:filter and map:for-each.

I think the argument is again consistency. If you can do…

```xquery
$map?[position() = 1]
```

…why shouldn’t one be able to do…

```xquery
map:filter($map, fn($i, $p) { $p = 1 })
```

**Comment by michaelhkay** [comment]
The difference is that providing position() in a map filter expression is achieved by removing a restriction; providing it in the map:filter function is achieved by adding a feature. Orthogonal language design means that you remove restrictions if they do no harm; that's different from adding an un-needed feature in one place because a similar feature is available elsewhere.

**Comment by ChristianGruen** [comment]
> The difference is that providing position() in a map filter expression is achieved by removing a restriction; providing it in the map:filter function is achieved by adding a feature. Orthogonal language design means that you remove restrictions if the restriction provides no benefit; that's different from adding an un-needed feature in one place because a similar feature is available elsewhere.

Maybe two things:

1. The map filter expression is a new feature (even if ressembles existing filters, and predicats in XPath step), so my perspective is that we are indeed adding positional access capability to the filter (whereas we don’t add EBV functionality).
2. It’s an assertion (no fact) that positional access in map functions is “un-needed”. In general, it can indeed be helpful to enumerate data even if it has no defined order.

**Comment by ChristianGruen** [comment]
You’re right, we shouldn’t introduce functionality for the mere sake of consistency; I’m closing this.
Thanks for sharing your perspective.
