### ISSUE TITLE
Node constructor vs. otherwise/map constructor

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1241]
I wonder whether we should care that the following expression could be interpreted in two ways:

```xquery
<🤔/> ! (element otherwise {})
```

The result could either be `<otherwise/>` or an empty map.

If we say it’s an edge case that we can ignore, it would be fine for me.

Before `otherwise` was introduced, we used `?:` in our implementation, analogous to Kotlin’s [Elvis operator](https://kotlinlang.org/docs/null-safety.html#elvis-operator). JavaScript now has `??` (which is no option for us).

**Comment by michaelhkay** [comment]
Interesting.

This isn't a problem introduced by "otherwise", it's a problem introduced by bare-brace map constructors. It's only specific to "otherwise" in that most keyword operators will produce a type error if one of the operands is a map. But you have to parse 

element div {}

before you can decide that it's a type error.

We can't ignore the problem, but I'm sure we can solve it pragmatically, as we do with other ambiguities like /*/*.

Michael Kay
Saxonica

**Comment by michaelhkay** [comment]
I think this requires a new extra-grammatical constraint, to the effect that if an expression starts with (element | attribute | processing-instruction | namespace), followed by an NCName, followed by a "{". then the expression is interpreted as a node construction expression, even when the NCName could be interpreted as a binary operator.

**Comment by michaelhkay** [comment]
Specifically:

Extra-grammatical constraint: named node constructors. If an expression starts with the three tokens (K N "{"), where K is `element`, `attribute`, `processing-instruction`, or `namespace`, and N is an NCName that could be interpreted as a binary operator (for example `div` or `otherwise`) then the expression is parsed as a node construction expression. For example `element otherwise {}` is read in XQuery as a computed element constructor returning an empty element node named `otherwise`; it is not read as an OtherwiseExpr.
