### ISSUE TITLE
fn:json-to-xml: `number-parser` option

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1246]
With #973, the `number-parser` option was added to `fn:json-to-xml`. It has been reported back to us that the current definition introduces a backward incompatibility:

```xquery
json-to-xml('1234567')
```

…now returns:

```xquery
<number xmlns="http://www.w3.org/2005/xpath-functions">1.234567E6</number>
```

Before, we got:

```xquery
<number xmlns="http://www.w3.org/2005/xpath-functions">1234567</number>
```

I’m convinced that the `number-parser` option is am important addition for `fn:json-to-xml` – I’ve already seen its application in practice – but I think we’ll need to change the default, which currently `xs:double#1`.

It seems sufficient to me to change `xs:double#1` to `identity#1`.

As a side note, [17.4.2 XML Representation of JSON](https://www.w3.org/TR/xpath-functions-31/#json-to-xml-mapping) still states that:

> The [fn:json-to-xml](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-json-to-xml) function creates an element whose string value is lexically the same as the JSON representation of the number.

…which means that the semantics of `number-parser` have not been incorporated in this section yet (my fault).

**Comment by michaelhkay** [comment]
There's another little issue here, namely the interaction with the option `validate=true`. We should make it clear that validation applies after any conversion done by the number-parser, and that it's not strictly the case that the original lexical form is retained when validate=true -- because the schema type is xs:double, you may get the result of converting string-to-double and then double-to-string.

But I agree that the default in the non-validating case should be to leave the value as-is.
