### ISSUE TITLE
New super/union type xs:binary?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#130]
I know we want to avoid in-depth changes in the type system. Still, now that we have `xs:numeric`, is there an obvious reason why we have no super oder union type for `xs:base64Binary` and `xs:hexBinary`? It would simplify the definition of many extensions functions a lot (e.g. in the EXPath Binary or File Module).

**Comment by rhdunn** [comment]
Given that we have the new item type aliases functionality, should we move the definition of `xs:numeric` into the static context section that talks about item type aliases? We can then define `xs:binary` there in the same way. For example:

> [Definition: `xs:numeric` is a built-in *type alias* mapped to `union(xs:integer, xs:decimal, xs:float, xs:double)`.]
>
> [Definition: `xs:binary` is a built-in *type alias* mapped to `union(xs:base64Binary, xs:hexBinary)`.]

We would also need to update the places elsewhere (e.g. in the data model spec) that mention `xs:numeric` to also include `xs:binary`. I don't see any issues with those, and they look to be editorial only changes.

**Comment by rhdunn** [comment]
That then has the added benefits that a) `xs:numeric` is now handled by well-defined mechanisms already in place within the language and typesystem, so is not a special case; and b) the changes do not affect the core type system model as the types are just definitions like those a user could create within their own XQuery/XSLT files.

**Comment by benibela** [comment]
Too many types are bad for performance

E.g. for each type, I have a 64-bit integer bitset that stores the outcome of `instance of `  for every other standard type. 

Now I have 61 types, when you add four more types, my entire system breaks down

**Comment by ChristianGruen** [comment]
@benibela If performance is an issue, you could have a look at a paper from Jens Teubner on Scalable XQuery Type Matching: https://openproceedings.org/2008/conf/edbt/Teubner08.pdf. It’s not the way how we implemented it, but I like the approach.

**Comment by rhdunn** [comment]
We should at least consider reframing the existing `xs:numeric` type in terms of the new features (local union types and type aliases). That way, it can also serve as an example to people reading the spec on how to define their own types like this.

We may even add this xs:binary type (or the other suggested type unions) as an example in the item type declaration parts of the spec per @dnovatchev's suggestion of adding more gems into the spec.

**Comment by michaelhkay** [comment]
Another candidate for a built in union type is the (date, dateTime, time) combo. But I think it's only worth adding these if we're going to use them in built-in function signatures; otherwise, it's just as easy for users to define them themselves. And sadly, I don't see a clean way of retrospectively redefining function families such as adjust-dateTime() to work with the union type, rather than having multiple variants.

**Comment by michaelhkay** [comment]
@benibela I use a bitset representation as well (called a UType) and it's ideal for unions of primitive types because they just correspond to new combinations of bits.

**Comment by michaelhkay** [comment]
An alternative approach is to make xs:hexBinary and xs:base64Binary mutually promotable, as we are proposing with xs:string and xs:anyURI. The benefit of relying on type promotion rather than a new built-in union type is that it works with existing functions, such as those in the EXPath binary module: we don't really want the effort of revising that module to use the new type (and to have different versions for XP31 and XP40).
