### ISSUE TITLE
Rendition of EBNF syntax scraps

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1396]
In the EBNF syntax tabulation, the column width available for the RHS of productions is rather limited, leading to excessive line wrapping, especially where the entire syntax is displayed in Appendix A.

I haven't been entirely successful in sorting this out, but record my experiments here.

(a) In the CSS stylesheet qtspecs.css line 169, change the padding from 30px to 10px

(b) remove all the non-breaking spaces that are inserted after the production number and around the `::=` operator. (Search for `::=` in xmlspec-2016.xsl

(c) get rid of the tbody element that surrounds each tr by putting the productions in a prodgroup, achieved by adding a prodgroup element around the line `<prodrecap id="BNF-Grammar-prods" ref="BNF-Grammar-prods"/>` (line 43 of ebnf.xml)

Unfortunately this doesn't seem to allocate extra width to the columns, it merely creates extra whitespace to the right of the table. I can't work out why that is happening.

Another step would be to remove the final right-hand column containing comments, instead moving the comments to be under the RHS of the production. But the logic here is complex...

Finally, a pragmatic move would be to reduce the length of the longest production names, such as `FunctionSignatureWithDefaults`, which bloat the width of the LH column.

**Comment by ndw** [comment]
I'll take a look. It might also be possible to limit the width of the left column and add a horizontal scroll bar for `FunctionSignatureWithDefaults` and other really long names. That's not ideal either, of course. It's a trade off.

**Comment by rhdunn** [comment]
a) I like this change. Maybe also remove it altogether from the first column -- i.e. `table.scrap td:not(:first-child) { padding-left: 10px; }` -- so it doesn't cause indentation along the margin.

b) I like this change as well.

c) I also support this change. AFAICT this doesn't impact rendering (as HTML supports multiple tbody elements), it just makes the markup cleaner.

I also support moving the comments to under the productions. -- There aren't that many comments, so including that extra colum adds unnecessary space, and the space there causes most of the comments to wrap. Experimenting by removing that column, I can get `ArgumentList` to fit on one line.

NOTE: The code is already adding additional rows for multiple comments (e.g. for the `FunctionCall` production), so that could possibly be adjusted to work for any comment instead of subsequent comments. That would allow the comments to be placed in the same column as the production body.

How this looks with these proposals/changes (by editing the markup in place):

![image](https://github.com/user-attachments/assets/303621f1-4a8a-45f6-96a1-3c04564d3f4d)

**Comment by michaelhkay** [comment]
Thinking about this again, I'm wondering if the production numbers are actually useful? We don't ever refer to them, either from within the spec or in our general working methods, and they aren't useful identifiers because they aren't stable. They also cause a nuisance because they lead to unnecessary diffs when the numbers change. Can we simply get rid of them?

**Comment by ChristianGruen** [comment]
> Can we simply get rid of them?

I’d be delighted to say goodbye.

**Comment by michaelhkay** [comment]
I'm trying to get rid of some of the unnecessary complexity in the way the grammar rules are published. Observations:

- There's (complex) logic in the stylesheet for handling `rhs` elements that aren't immediately preceded by an `lhs`. But (a) the logic looks wrong, and (b) there are no such elements in xquery-assembled.xml.
- The stylesheet treats `com|constraint|gc|vgc` as interchangeable, but the only one of these that we use is `com`.
- The stylesheet handles `prodrecap` elements, but there are no such elements in xquery-assembled.xml. It contains only `prod` elements. The source document contains `prodrecap`, but this gets turned into `prod` by `assemble-spec.xsl` (which invokes `grammar2spec.xsl`). The `grammar2spec` stylesheet also allocates production numbers in an @num attribute, which xmlspec-2016.xsl ignores: it generates new numbers.
- The stylesheet xmlspec-2016.xsl has template rules in mode='ref' for the `prod` and `lhs` elements. This mode appears to be unused.

**Comment by michaelhkay** [comment]
The changes have been applied.
