### ISSUE TITLE
Invisible-xml function: why is $grammar of type item()?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1404]
In the `invisible-xml` function, the $grammar argument has type `item()?`. There's no evident reason why it isn't `xs:string?`; there's no clue in the specification or example what it might mean to supply something that isn't a string (or an empty sequence).

Note that declaring it as `item()` rather than `xs:string?` suppresses atomization of the supplied value.

**Comment by ndw** [comment]
Just me trying not to close any doors, but failing to think about atomization in the moment. I'll make a PR to fix it.

**Comment by AlainCouthures** [comment]
It would allow to directly provide the document resulting from the iXML grammar parsing for more performance. --AlainLe 27/08/2024, 23:12 Michael Kay ***@***.***> a écrit:

  
  In the invisible-xml function, the $grammar argument has type item()?. There's no evident reason why it isn't xs:string?; there's no clue in the specification or example what it might mean to supply something that isn't a string (or an empty sequence).
  Note that declaring it as item() rather than xs:string? suppresses atomization of the supplied value.

**Comment by michaelhkay** [comment]
If there's a deliberate intention to allow, for example, an XML representation of the iXML grammar, then I've no problem with that so long as it's explained.

**Comment by ndw** [comment]
Indeed. I may have jumped the gun. It's not unreasonable for the input grammar to be in XML. I think. I will write a test for that :-)
