### ISSUE TITLE
Byte ordering of CRC-32 hash result

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1426]
Test case hash-str-034 takes a 150,000-character string consisting of 50,000 repetitions of the string "ABC", and computes its CRC-32 hash value.

On Java the result comes back as decimal 105475755, which we translate to 0x06496EAB

On C# the result comes back as a 4-byte array AB 6E 49 06. My guess is we need to reverse the byte order, but I'd like to understand why...

I guess we need to say something about byte ordering, but what?

I tried to find the definitive specification. We simply point to IEEE 802.3 without a specific URI or section or version number. 802.3 actually appears to be a large family of standards. Can we do better than that?

I'm interested to know whether the specification actually defines the result to be a 32-bit (unsigned?) integer rather than an array of four bytes. If that's the case, then our spec needs to say how the 32-bit integer is converted to a sequence of 4 octets, which is what fn:hash actually returns. The C# example shows that there's more than one way of doing it.

**Comment by Arithmeticus** [comment]
https://docs.amd.com/v/u/en-US/xapp209

**Comment by ChristianGruen** [comment]
As far as I can see (and I cannot see a lot because the document is not freely available), IEEE 802.3 defines CRC-32 in the context of network packet transmission. How the result is presented seems not to be defined, which is why it depends on the programming language. 

While Java chooses a network byte order (Big-Endian) byte array representation, C# seems to return a Little-Endian byte array, perhaps because it is the internal representation for integers on Intel-based architectures (just a guess).

This means we should probably define the endianness in the spec (I have only experienced Big-Endianness so far, which is used by Java, Python or Perl). In addition, we could offer an option to make it adjustable.

**Comment by michaelhkay** [comment]
>https://docs.amd.com/v/u/en-US/xapp209

I can find plenty of documents that describe the algorithm in gory detail, but I'm having trouble finding a definitive reference that we can cite. It seems to be one of these things like Base64 or URI syntax - lots of folklore, quite a few variations, no definitive spec.
