### ISSUE TITLE
Arguments that have a default value but don't accept ()

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1458]
The following functions define an argument that has a default value, but don't allow () to be supplied explicitly:

```
lang
id
element-with-id
idref
parse-html
```

As determined by running the following query against the function catalog:

`//*:arg[@default and not(ends-with(@type,'?') or ends-with(@type, '*'))]/(ancestor::*:function/(@prefix||':'||@name))`

There are others which this query doesn't pick up, mainly where the defaultable argument is a function, including:

array:build
map:build
array:get
map:get
fn:highest
fn:lowest

**Comment by ndw** [comment]
In fact, the prose has become a little tangled. Looking at `id` as an example, we find:

> `E` is in the target document. The target document is the document containing `$node`, or the document containing the context value (`.`) if the second argument is omitted.

That reads a little oddly because if the second argument is omitted, it will now get an explicit default value, and that doesn't feel quite like "omitted".

I'm not sure if your observation implies a proposal that they should allow `()` as an explicit value, but assuming it does...

I'm not sure. You'd get:

* `id('foo')` => `id('foo', .)`
* `id('foo', .)` => `id('foo', .)`
* `id('foo', ())` => `id('foo', .)`

I think I'd prefer not to provide a default and have the semantics as they're currently written (because that was the status quo when they were written) or to provide a default and to make it an error to pass `()` explicitly. The `id` function *needs* a context, if you pass an expression that happens to evaluate to the empty sequence, that's more likely to be an error than to be "use the document that contains the current context value". IMHO.

I think similar reasoning holds for `lang`, `element-with-id`, and `idref`.

For `parse-html` the option is a map. If we allow an explicit empty sequence, we have to decide what it means. On thirty seconds thought, I think the simpler thing is just not to allow it there either.

**Comment by ChristianGruen** [comment]
This one may catch some more cases:

```xquery
//*:arg[@default and matches((@type, @type-ref), '^fn|[^?*]$')]
  /ancestor::*:function ! (@prefix || ':' || @name)
```

**Comment by ChristianGruen** [comment]
Regarding `fn:lang` etc., I agree with Norm (see, among others, https://github.com/qt4cg/qtspecs/issues/951).

**Comment by michaelhkay** [comment]
Yes, I think you're probably right that where the default is ".", we shouldn't apply the default if () is supplied explicitly.

Apart from anything else, a user-defined function can't reproduce this effect - if () is supplied, then the function has no way of discovering the context item of the caller.
