### ISSUE TITLE
Understanding the xsl:array constructor

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#1468]
In reading the XSLT specs on the `xsl:array` constructor (#406 adopted at meeting [28](https://qt4cg.org/meeting/minutes/2023/03-28.html#pr-406)) I find myself somewhat confused. Either I need to be illumined, the specs need to be clarified, or some other adjustments are needed.

First, I'm still struck by the disparity between maps and arrays; there's a `xsl:map-member` but no `xsl:array-member`. That horse has been beaten many times, I know. But I need to record that the disparity is very noticeable. The disorientation is aggravated by the second example in the [constructor overview](https://qt4cg.org/specifications/xslt-40/Overview.html#array-construction):

```
<xsl:array use="?value">
   <xsl:for-each-group select="0 to 19" group-adjacent=". idiv 4">
     <xsl:map-entry key="'value'" select="current-group()"/>
   </xsl:for-each-group>
</xsl:array>
```

A map entry within an array? This just strikes me as a hack, and is suggestive of a design flaw in the language. (I know what you're about to say in response; hold that thought...) That's exacerbated when I see example 2c invoking an array constructor within an array, only to get rid of the nested array to get at what you wanted in the first place, the items grouped into members.

Furthermore, the value of attribute `@use`, `?value`, is cryptic. Yes, I get what's going on, but the first several times reading it I thought it was very abracadabrish. And that same feeling hit me for the other examples' values of `@use`: `.()` and `?*`. The `.()` bit of syntax appears only twice in the specs (here), without explanation.

If `@use` is evaluated once for every item, then in example 2b...
```
<xsl:array use=".()">
   <xsl:for-each-group select="0 to 19" group-adjacent=". idiv 4">
     <xsl:sequence select="current-group#0"/>
   </xsl:for-each-group>
</xsl:array>
```
...I would expect the expression `.()` to be applied to twenty items, because a sequence of five sequences of four items each is simply one sequence of twenty items, innit? Or are we allowed here and only here for a sequence constructor to create a sequence of sequences?

It seems that `@use` is striving to do something similar to `@group-by` in `xsl:for-each-group`. But it isn't. Understanding the goal is obfuscated by the vague name. Use what, to what end?

Overall, I feel that the array constructor is a 2nd-class citizen in the specs. I love using the map constructor in XSLT: it tells users very clearly what's going on. I don't look forward to the using the array constructor in XSLT, because I think it does the opposite. But maybe I'm wrong.

I don't have a specific proposal to fix, because I understand some of the conceptual hurdles to a putative `xsl:array-member`. Still. I can't help but wish that that's what we had.

**Comment by Arithmeticus** [comment]
Yes, I realize that one of my comments above misreads `<xsl:sequence select="current-group#0"/>` as `<xsl:sequence select="current-group()"/>`. But that misreading just points to the larger underlying problem: the only way to create non-singleton arrays is through what strikes me as legerdemain.

**Comment by michaelhkay** [comment]
I share your view that the design is imperfect; I'm very open to ideas that improve it, as I've been round it many times without find a solution that I'm 100% happy with.

I think there's a constraint that the instructions in a sequence constructor have to generate a sequence of items that are combined together using sequence concatenation. Otherwise, for example, use of xsl:for-each or xsl:apply-templates within an array constructor becomes hopeless.

For the design of xsl:map in 3.0 we decided that those items should be maps, which the xsl:map instruction would merge; and for convenience we introduced xsl:map-entry as a handy way of creating a single-entry map.

For constructing arrays, it's less clear what the constituent items should be. The reasoning behind the current design is:

* A common use case is constructing an array where each member is a singleton item. This works well with the current approach, it is the default if `xsl:array/@use` is used.
* If you want to construct arrays in which members have non-singleton cardinality, then we need to provide some way of parcelling each member value up as an item. There are various ways we (or the user) could do this, for example the parcel wrapping a member $M could be:
** An array [$M]
** A value record {value: $M}
** A function item fn(){$M}

An alternative design, which I have tried, is to select one of these approaches, to introduce an instruction `xsl:array-member` that does the parcelling-up, and to make `xsl:array` only accept input as a sequence of such parcels.

I've also experimented with ideas for making "parcels" a primitive, allowing this to be rather more strongly typed.

The current design is in some ways a cop-out; it says we can't decide on a single standard way of parcelling that suits everyone all the time, so do it any way you like, and provide a `use` function that does the unparcelling of your chosen format.

**Comment by ndw** [comment]
What is bad or awkward about the design that says the `xsl:array` only accepts a sequence of `xsl:array-member`s?

**Comment by michaelhkay** [comment]
>What is bad or awkward about the design that says the xsl:array only accepts a sequence of xsl:array-members?

How would you create an array in which the number of members is not known statically?

**Comment by ndw** [comment]
I was naively assuming that I could return `xsl:array-member` instructions from other sequence constructors, I guess.

**Comment by michaelhkay** [comment]
The reason I prefer `{value: $M}` as the parcel format, in preference to `[$M]`, is primarily that it's more likely to lead to a helpful error message if you get it wrong. It creates a bit of type safety.

**Comment by michaelhkay** [comment]
Related to #826

**Comment by michaelhkay** [comment]
I've done a revised design in which the xsl:array instruction can select EITHER a sequence of atomic items OR a sequence of arrays OR a sequence of value records, and in which an xsl:array-member instruction can be used to create value records so the user doesn't have to be consciously aware of them.
