### ISSUE TITLE
What is the status of fn:current-mode() in XSLT?

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#1590]
It appears in the function catalog but not in the specification.

**Comment by michaelhkay** [comment]
I think you meant current-mode() (mentioned in phone call this morning). Corrected the title.

It looks half-baked, because much of the text has been copied from current-output-uri and is clearly inappropriate.

So I think the status is essentially "commented out text" - text that was drafted, for some reason, but not approved by the group for inclusion in the spec.

I do vaguely remember people asking for a function that returned the name of the current mode, but I can't find an issue relating to it. I can see some people finding a use for it and I don't see any technical difficulties in providing it.

**Comment by ndw** [comment]
Yes, I did mean `fn:current-mode`, sorry about that. I noticed because the list of functions comes from the catalog but when I happened to click on that one testing the new finder interface, it didn't go anywhere. On a quick analysis, that's the only function in the catalog not in the spec.
