### ISSUE TITLE
Handling of duplicate keys in xsl:map

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#169]
The draft specifications include proposals to enhance the handling of duplicate key values in xsl:map. This issue seeks WG endorsement of these changes.

See XSLT section 21.2.1

map:merge currently provides a set of fixed "policy" options for handling of duplicates; xsl:map always raises an error.

Rather than adopt the fixed set of policies in map:merge, I propose that xsl:map should accept a callback function to process duplicates. For example, forming a sequence-concatenation of the values can be achieved using `on-duplicates="op(',')"`. This approach allows all the options provided by map:merge, and more; for example the duplicate entries can be combined using string-join() if so desired.

**Comment by graydon2014** [comment]
https://www.saxonica.com/papers/xmlprague-2020mhk.pdf says "the required
type is a function with arity 2" and seems to presume that there will be
only two duplicates, rather than potentially arbitrarily many
duplicates. (But of course the proposal may have evolved since.)

Would
```
<xsl:map on-duplicates="function($x as item()+, $y){head($x)}">
```
work?

Would
```
<xsl:map on-duplicates="function($x as item()+, $y){$x[$y]}">
```
? (I have no idea why I'd want to do the second one, but it leaps to mind
with a required arity of 2.)

I have fairly often wanted to group all the examples of something under
a key; everything with a date in June, everything with a level depth of
three, stuff like that.  It'd be extremely convenient if
`xsl:map/@on-duplicates` allowed for this kind of "everything with this
key maps under this key" use case.

**Comment by michaelhkay** [comment]
The idea is to support a single-pass operation where, when you encounter a duplicate, you decide what to do with it there and then. The two arguments are (a) the current value (which may result from previous processing of duplicates), and (b) the new value, and you're expected to combine them into a new current value. If you want to build a sequence containing all the values you can use `function{$x,$y){$x, $y}`. In that sense it's rather like fold-left where you build the result incrementally by processing one item at a time and combining that item with the result of previous processing.

**Comment by michaelhkay** [comment]
The effect of `use-any` is to select any one of the duplicates at the processor's discretion. I suspect you really want the `combine` option, and that's achieved by `on-duplicates="function{$x,$y){$x, $y}"`. This gives you a map entry containing the sequence-concatenation of all the values supplied for the key.

**Comment by ndw** [comment]
The group accepted this as the status quo at [meeting 056](https://qt4cg.org/meeting/minutes/2023/11-28.html).
