### ISSUE TITLE
Should we allow f(x,,y) when calling a function where parameter 2 is optional?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#174]
If the second and third parameters of a function are optional, should we allow the syntax

`f(x,,y)`

to call the function using the default value for the second parameter?

I can see this being a handy convention for calling `fn:sort`, for example, where defaulting the second parameter (the collation) is commonplace.

The current proposal does not allow this, but I see no good reason not to.

**Comment by ndw** [comment]
It's easy to specify and easy to implement, but does it make the language easier to use? Allowing more and more syntactic variation to be intepretable as valid syntax doesn't always make things easier for users. Am I more likely to accidentally have typed `,,` or to have meant "use the default value for the second argument"?

I think `f(x,,y)` looks like an error. If the goal is to allow the "middle" argument to be left out and take on its default value (without putting the default in explicitly because then, uhm, it isn't a default anymore), I'd be happier if there was some explicit bit of syntax I could put in there, `f(x, #default, y)`. (I'm not proposing `#default` really, I'm just using it as an example.

**Comment by ChristianGruen** [comment]
To me, the representation looks confusing; but maybe I’m just not used to it. Multiple commas can easily occur as typing errors, and they would then get legal; and we don't save too much space either.

Maybe things get better anyway if we have named parameters?

If we decide to allow this, I believe we should be consistent and allow it everywhere else where we can have empty sequences with commas, e.g. in lists:

```xquery
1, 2,, (: 3… might be helpful if comments are used :), 456

**Comment by dnovatchev** [comment]
> If the second and third parameters of a function are optional, should we allow the syntax
> 
> `f(x,,y)`

If we allow this, one would need to count the number of consecutive commas, and this is really annoying and error-prone.

In any such case I would prefer:

**_`f(firstArgName := x, thirdArgName := y)`_**

in which case I don't care to write any (how many ???) commas.

**Comment by michaelhkay** [comment]
Proposal withdrawn as it seems the consensus is against allowing this.
