### ISSUE TITLE
for expression: "at" keyword

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#231]
In a the **_[comment thread](https://github.com/qt4cg/qtspecs/issues/181#issuecomment-1304604772)_** to #181 it was noticed that to be in line with that proposal, we also need to be able to access the index of any member variable within a **_["for expression"](https://qt4cg.org/pr/230/xquery-40/xpath-40-autodiff.html#id-for-expressions)_**.

This can be done in various ways, such as with an **_`index()`_** function, as in the code example below:

```xq
for $x in (1,  3, 5, 7, 9, 11),
    $y in (1,  3, 5, 7, 9, 11)
 return
     if(index($x) le index($y)) then [$x, $y]
       else ()
```

But fortunately, in XQuery there is already the **_["at"](https://qt4cg.org/pr/230/xquery-40/xpath-40-autodiff.html#id-for-expressions)_** keyword serving exactly the same purpose. Thus the above expression can be written as:

```xq
for $x at $ind-x in (1,  3, 5, 7, 9, 11),
    $y at $ind-y in (1,  3, 5, 7, 9, 11)
 return
     if($ind-x le $ind-y) then [$x, $y]
       else ()
```

Thus, I am proposing just to allow the **"at"** keyword in XPath **_[for-expressions](https://qt4cg.org/pr/230/xquery-40/xpath-40-autodiff.html#id-for-expressions)_**.

**Comment by michaelhkay** [comment]
This proposal re-opens old wounds. There's always been a tension between those who would like XPath to offer everything that XQuery offers, and those who would like to keep XPath small. The "keep it small" proponents tend to lose the battle one feature at a time. Rather than make such decisions one feature at a time, we really ought to have a vision for what we want XPath to be. Why do we have a language that's separate from XQuery at all? Without having a shared view of the purpose of the language, it's very hard to make this kind of decision in any rational way.

One vision for XPath is that its primary role is as a sublanguage within XSLT (and XSD and XProc...), and new features should be considered primarily from the viewpoint of the typical XSLT user. That involves considering how much duplication of functionality between XSLT and XPath is appropriate, and where there is unavoidable duplication, ensuring as much semantic consistency as possible.

Obviously if we want to do it we should do it the XQuery way, with an "at" clause, rather than inventing something new.

**Comment by michaelhkay** [comment]
The proposal has been implemented.
