### ISSUE TITLE
Function fn:differences

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#316]
I didn't see any issues thread devoted `fn:differences()`, so am opening this one. Please respond with xrefs to anything relevant.

Draft here:
https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-differences

IMO, this function seems overly complicated for both users and implementors. The specs provide difficult reading. But it is the first function to try to address the desideratum for differencing. Something like it is needed methinks.

My suggestion would be to simplify the function as a straightforward string comparison, i.e., change the signature to something like `fn:differences($input1 as xs:string, $input2 as xs:string) as OUTPUT` where `OUTPUT` is either a tree structure (like the output of `fn:analyze-string()`) or a sequence of records (e.g., `(is-in-1 as xs:boolean, is-in-2 as xs:boolean, fragment as xs:string)`).

Such a change would make the function more tractable for both users and implementers. The user, would need to cast each sequence to a string, and in so doing will be able to (be compelled to) make fine-grained decisions on things such as normalization. Processor implementers have far simpler input, and they can choose the difference algorithm that makes best sense at the moment.

One counterargument might be that the resultant output would be difficult to correlate to the original sequences. Ostensibly, one wants to do things such as decide whether to drop certain items in sequence 1 or sequence 2. My response is that the current draft results in output that suffers from the same problem. Navigating the map to correlate it to the original sequence sounds daunting. With my suggestion, there are ways around this, through auxiliary functions or arity expansions that normalize the output. 

But I don't want to get postprocessing output here, which would be tangential to the main question, i.e., how `fn:differences()` should be constructed in a way conducive to both users and implementers.

**Comment by michaelhkay** [comment]
Thanks for the contribution. The design of this function certainly needs further work.

Another approach would be to generate a document with difference markup, e.g. as per https://metacpan.org/pod/XML::DifferenceMarkup.

Both the specification and the implementation (and writing tests!) are likely to be a significant amount of effort if we decide to go ahead with this function. But I have no doubts that it would be useful.

**Comment by dnovatchev** [comment]
Maybe we need to consult **_[Philip Fearon](https://app.slack.com/client/T011VK9115Z/C01GVC3JLHE/rimeto_profile/U0126SM6KTN?cdn_fallback=2)_** (DeltaXML) in order not to rediscover the wheel?

Also, the signature at https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-differences declateres the first two arguments to be of type `item()`  but the Summary tells us these are sequences ???

**Comment by michaelhkay** [comment]
I'm wondering about a much simpler function that locates the first difference between two document nodes.

Defined something like this:

The function `differences(A as document-node(), B as document-node())` returns an empty sequence if A and B are deep-equal. Otherwise it returns a sequence of 1 or more maps. The first of these maps contains information about the first difference between A and B, as defined below. Subsequent maps are optional and if present contain information about further differences, but the content of maps beyond the first is implementation-dependent. The first map in the result is found as follows:

(1) Consider the attributes of A, in document order. If there is a pair of attributes (AA, BB) that have the same name but are not deep-equal, select one such attribute pair, and return map{0: AA, 1:BB}. Otherwise, if there is an attribute AA in A that has no like-named attribute in B, return map{0:AA}. Otherwise, if there is an attribute BB in B that has no like-named attribute in A, return map{1:BB}.

(2) Consider the children of A and the children of B, in document order, skipping any pairs of child nodes that are deep-equal to each other. For the first pair of child nodes (P, Q) that are not deep-equal: if they are elements with the same name, return difference (P, Q). Otherwise, return map{0: P, 1: Q}. If A has more children than B, and the first "extra" child of A is X, return map{0: X}. If B has more children than A, and the first "extra" child of A is Y, return map{1: Y}. If A and B are different for any other reason, return  map{0: A, 1: B}.

Each returned map may include an additional field "comment" that contains an implementation-dependent description of the difference encountered.

**Comment by Arithmeticus** [comment]
The proposed approach will probably need to address the following:

- how does pairing work, and what happens when a pairing operation on AA lends itself to multiple matches, BB1, BB2, etc., or where AA is deeply identical to other nodes in document A?
- are attributes or children to be paired independent of the identity of their parents? I can see situations for both yes and no.
- related, by "children" I have assumed "descendants", but if that's not the case, clarification is required on what is meant by "children" of a document A or B.
- If documents A and B differ only because of a leafmost node (`node()[not(node())]`), all its ancestors will register a difference. That could prove to be a lot of unnecessary noise. It is worth designing the specs to exclude excessive results.

On the question of input:

ISTM that the process of comparing document to document can be profitably simplified. Let there be an alphabet allocated into blocks, one block for each node type. _(Presume, for the time being, we are not limited to the 1.1M+ characters of Unicode. There is a workable adjustment even where we adopt that limitation.)_ For document A and document B create two sequences of all descendant nodes. Create an empty signature-to-letter map to remember upcoming substitutions. For each node in each document sequence get the serialized signature (say its hash value). If the signature has already been assigned to a letter (consult the signature-to-letter map), then replace the node with that letter, otherwise replace the node with the next letter available in the block, and add the new assignment as an entry to the signature-to-letter map. Under this process, documents A and B can each be reduced to a string. As long as the assignments are documented, the process is losslessly reversible. The differencing problem can now be expressed/simplified as a string comparison problem. 

I frame the problem this way not to specify how the output should be generated but to catalyze two aspects of the editorial process. 

First, to simplify discussion. Many problems in tree-to-tree differencing can be expressed as problems in string-to-string differencing. Those that cannot normally pertain to postprocessing analysis. 

Second, to think outside the box about new XPath functions. The core algorithm required to handle `fn:differences()`, whatever the function's design, will be significant. That same core algorithm could be applied to a variety of types of pairwise comparison: document to document, item-sequence to item-sequence, and string to string. In other words, alternatives to the type of input for `fn:differences()` should be treated not as competing but as complementary, and I recommend thinking about designing the new function(s) so as to support users coming from different directions.

**Comment by dnovatchev** [comment]
I think it my be useful in certain cases, if `deep-equal()` in the cases when the result is `false()` could also return the result of `differences()`. We could achieve this by adding a new parameter to the function definition: `return-differences = false()`

Just an idea 😄

**Comment by michaelhkay** [comment]
I have raised PR #551 to drop the function.
