### ISSUE TITLE
Add a namespace uris option to fn:path

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#332]
The output of `fn;path` using namespaces is very verbose as it is specified to use the `Q{uri}name` syntax. It would be useful if it was extended to take a namespace prefix to uri map.

1. Add a second `$namespaces` parameter that has the type `map(union(xs:NCName, enum('')), xs:anyURI)` (the same as fn:in-scope-namespaces) -- this will have a default value of `map{}` to preserve the existing behaviour.
2. If the namespace uri is in the map, use the given prefix. If that prefix is "" then just use the local name.
3. If the namespace uri is not in the map, use the `Q{uri}name` syntax.

This allows for things like `fn:path($e, namespaces := fn:in-scope-namespaces())`.

**Comment by michaelhkay** [comment]
Makes sense. The rules need to allow for the supplied map binding two prefixes to the same URI (just choose one of them arbitrarily).

**Comment by ChristianGruen** [comment]
Maybe we could introduce an `$option` argument and add some more features, e.g. `positions` (xs:boolean) for adding/omitting the positional predicates in the output.

**Comment by michaelhkay** [comment]
Yes, but I wonder whether packaging options together in an `$options` argument is still worth doing now we have optional parameters and keyword arguments?

**Comment by ChristianGruen** [comment]
I'd prefer $options. Function signatures may stay more compact that way (I'm just thinking of fn:deep-equal…), and it may still allow us to use the conventional syntax without supplying the full sequence of positional arguments. Next, option maps can be bound to variables and referencd multiple times.

Besides, I think we still need to allow map keys to be supplied as keyword arguments (but that's just a matter of time, I guess).

**Comment by michaelhkay** [comment]
The in-scope namespaces of an element always include the xml namespace, so perhaps that should be reflected in the default?

It's not clear when a no-namespace element `E` should be represented as `E` and when it should be represented as `Q{}E`.  Given `<E><F></E>` with no namespaces, `in-scope-namespaces($F)` is going to be an empty map (except for the xml namespace) which is indistinguishable from the default. So how do we decide whether to output `Q{}E[1]/Q{}F[1]` versus `E[1]/F[1]`? I think the answer is for the default for the $namespaces argument to be `()` rather than `map{}`.
