### ISSUE TITLE
[FO]The `union ( | )`, `itersect`, `except`  and `combine (,)` operators are not mentioned in the F & O. Have not the best categorization in the XPath spec.

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#35]
1. Searching the F & O document for the `union ` ( `|` ), `intersect ` and `except` operators finds 0 occurrences. Neither can `,` be found, and of course, it is unsearchable.

2. In the XPath spec these are described in section "4.7.3 Combining Node Sequences". The word node-set is not mentioned at all and this is misleading, because the `union ` ( `|` ), `intersect ` and `except` operators are in fact set-operators, or at least set-generating operators.

Thanks,
Dimitre

**Comment by michaelhkay** [comment]
This is purely editorial, and I doubt there will be enough effort available for a wholesale reorganisation of the specs. It would also have the downside of making it much harder for readers to identify changes.

**Comment by dnovatchev** [comment]
> This is purely editorial, and I doubt there will be enough effort available for a wholesale reorganisation of the specs. It would also have the downside of making it much harder for readers to identify changes.

This is not just purely editorial. Operators are on datatypes. Thus, **hiding or improperly representing operators means hiding or improperly representing datatypes**.
In this particular case, the word "**set**" (as in "node-set") has magically disappeared. On one side the spec is trying to hide de facto existing sets and set operators, on the other side it uses in more than one place a flow of narrative to describe again and again what simply can be said as "when the sets are equal".

And this attempt to call what is more strictly a **set** (node-set) led to hiding the real, most strict type of node-sets. One of the reason for the specs to be so huge...

This error needs to be corrected.

**Comment by ChristianGruen** [comment]
Maybe I didn't read the spec in detail by myself back then, but I never considered the lack of set terminology as an “error”. For me, XQuery and future versions of XPath were/are all about sequences, and there are just a few operators that generate sets. In addition, nodes may need to be in document order, so it would not be sufficient anyway to e.g. call the results of e.g. the union operator “sets”. Having a concise term for these types of node results was the only thing I sometimes missed (in some papers, the term DDO is used, for “distinct document order”).

But more important: In practice, except from implementors, hardly anyone reads a language specification in detail. Reworking the specifications sounds like a lot of work, and I’m not sure who’ll eventually benefit from it.

**Comment by dnovatchev** [comment]
On Mon, Dec 21, 2020 at 11:32 PM Christian Grün <notifications@github.com>
wrote:

But more important: In practice, except from implementors, hardly anyone
> reads a language specification in detail. Reworking the specifications
> sounds like a lot of work, and I’m not sure who’ll eventually benefit from
> it.
>
>
When a new feature is proposed, that is widely available and used in the
most popular programming languages, *the intent is not to ease the work of
the specification writers, but it is to give the developers new, useful
functionality* that they are accustomed to having in C# / Java / Python /
SQL, but miss in the XPath / XQuery / XSLT.

Word tells me that the XSLT 3.0 specification is 1108 pages long. An effort
to add a feature description on 10 new pages will increase the length of
the document with less than 1%.

Thanks,
Dimitre

**Comment by ChristianGruen** [comment]
> When a new feature is proposed […]

I cannot see which new feature you are proposing in the scope of this issue.

I assume you were misinterpreting my comment, and you possibly wanted to communicate to me that the changes your are suggesting here are mandatory to make #34 happen?

**Comment by dnovatchev** [comment]
> ... you possibly wanted to communicate to me that the changes your are suggesting here are mandatory to make #34 happen?

@ChristianGruen,  as you mentioned the word "set" more than once in your initial comment in this thread, I was assuming that you were in context.

**Comment by michaelhkay** [comment]
To return to the original comment:

(1) Searching the F & O document for the union ( | ), intersect and except operators finds 0 occurrences. Neither can , be found, and of course, it is unsearchable.

In the 2.0 spec these were described by pseudo-functions such as op:union, referenced from the Operator Mapping Table in the language spec, along with other operators such as "<<" and ">>". Unfortunately, though (a) there were other operators such as "is", "and", and "or" that were not defined this way, and (b) (more seriously) the description of these operators in the language spec actually defined them directly, without reference to the operator mapping table and the definition in F+O. So in 2.0, there were two definitions of these operators, and it wasn't made clear which of them was normative. The decision was therefore made that only the polymorphic operators (in particular, arithmetic operators and value comparison operators) should be defined in F+O, and for other operators, the definition in the language spec would be self-contained.

(2) In the XPath spec these are described in section "4.7.3 Combining Node Sequences". The word node-set is not mentioned at all and this is misleading, because the union ( | ), intersect and except operators are in fact set-operators, or at least set-generating operators.

These operators operate on arbitrary node sequences (which may contain duplicates), and the order of the results is well defined. So although they behave in a way that is closely analogous to mathematical set operators, neither the operands nor the result (in 2.0) is a true set, and it would be misleading to describe it as such; that's why the term node-set is no longer used.

You're confusing people in this thread by not making it clear whether your comment is editorial or substantive. If you want to propose technical changes to the language, such as new data types or operators, please make it clear what you are proposing. On the other hand, if your comments are purely about the arrangement or readability of the text or the choice of terminology, then please make it clear that your comment is editorial.

**Comment by dnovatchev** [comment]
@michaelhkay 

> You're confusing people in this thread by not making it clear whether your comment is editorial or substantive. If you want to propose technical changes to the language, such as new data types or operators, please make it clear what you are proposing. On the other hand, if your comments are purely about the arrangement or readability of the text or the choice of terminology, then please make it clear that your comment is editorial.

The issue has two points:

 Point 1 is editorial. I agree with your use of the word "Unfortunately" to refer to the current problem of specifying some operators and not others in both documents. Let's correct this.
 
 Point 2 may not seem relevant for the current set of specification documents, but will definitely become an issue when set support is added in XPath 4. I still believe that at least some text needs to be added that clarifies the difference between sets (which we do have in XPath 2+, although they have an added ordereing), sets with ordering (which we do have) and general sequences, which are not sets, because they can contain duplicate items. It would be good to define the set-producing operators as operators that produce sets with ordering, thus not general sequences.
 
It is really amazing how much some people are afraid from the word "set".

**Comment by benibela** [comment]
>It is really amazing how much some people are afraid from the word "set".

Set is the god of deserts, storms, disorder, violence, and foreigners, who killed and mutilated his own brother Osiris. That makes people afraid for good reason

**Comment by dnovatchev** [comment]
> It is really amazing how much some people are afraid from the word "set".
> > Set is the god of deserts, storms, disorder, violence, and foreigners, who killed and mutilated his own brother Osiris. That makes people afraid for good reason

Also it is the god that can shrink a  document of 1108 pages into 300.

**Comment by ChristianGruen** [comment]
Perfect, so we found the guy who’ll do the job!

**Comment by michaelhkay** [comment]
"Set" is unfortunately also the word with the greatest number of distinct meanings in the English language.

Happy Christmas all!

Michael Kay

**Comment by dnovatchev** [comment]
Happy Christmas Dr. Kay and all readers!

Dimitre
