### ISSUE TITLE
serialization indent whitespace

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#358]
There could be an option to control whether the serialization indents with space or tabs, and how many of them (e.g.  2 or 4 spaces )

Related: https://github.com/qt4cg/qtspecs/issues/101

A user request: https://github.com/benibela/xidel/issues/100

**Comment by ChristianGruen** [comment]
We could add the following serialization parameters:

Parameter | Description | Values
--- | --- | ---
`tabs` | Use tabulator characters instead of spaces for indentation | `yes`, `no`
`indents` | Number of indentation characters to be inserted | *integer*
`indent-attributes` | Indent multiple attributes (similar to [HTML Tidy’s configuration option](http://api.html-tidy.org/tidy/quickref_5.0.0.html#indent-attributes)) | `yes`, `no`
`line-ending` | Newline character (see #101) | `0x*A`, …

**Comment by michaelhkay** [comment]
Could combine "tabs" and "indents" with say

`indent-unit="\s\s\s"`

or

`indent-unit="\t"`

**Comment by IgorEisberg** [comment]
> Could combine "tabs" and "indents" with say
> 
> `indent-unit="\s\s\s"`
> 
> or
> 
> `indent-unit="\t"`

A bit redundant, I think, considering that the only valid indentation characters are spaces and tabs.
Also having
`indent-unit="\s\s\s\s"`
or
`indent-unit="    "`
or for 8 spaces (for whoever even wants it)
`indent-unit="        "`
doesn't look good on the eye.
I'm all for --tabs and --indents. Custom characters are simply not valid.

**Comment by michaelhkay** [comment]
I think it would be better (simpler) to do this with one parameter rather than two. We could avoid the backslashes and use indent-unit="SSSS" for spaces or indent-unit="T" for tabs.

**Comment by ChristianGruen** [comment]
I agree. If a tab is selected as an indentation character, the unit will usually changed as well to `1`.

I believe that using already known syntax would simplify the usage (`\t` and `  `, possibly `\s\s`).

**Comment by ChristianGruen** [comment]
Closed in favor of #1234.
