### ISSUE TITLE
fn:deep-equal: Using Multilevel Hierarchy and Abstraction when designing and specifying complex functions

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#399]
Whenever a function is too-complex, its precise and clear specification becomes problematic and the complexity results in huge volume of text that is difficult to fathom, understand and the correctness of whose meaning becomes less and less obvious.

Solving this problem would benefit all groups of readers, be they future implementors or just curious XPath enthusiasts.

Here I present one well-known and successfully tried in practice solution, which the Romans summarized in the phrase: "**_Divide et Impera_**" ("Divide and conquer")

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Philip-ii-of-macedon.jpg/330px-Philip-ii-of-macedon.jpg"/>

Below is one possible splitting of the functionality of **[fn:deep-equal](https://qt4cg.org/pr/395/xpath-functions-40/autodiff.html#func-deep-equal)** into different smaller and simpler functions on 5 levels, each level possibly dispatching to a function on  another level. The intermediate-level functions each have their own value and could be used independently of **fn:deep-equal** and of each other. Even though there is the possibility of recursion, we can still get a simple picture and immediate understanding of this functionality, just playing with the following collapsible/expandable representation (click on the corresponding arrow), which fits on a single screen:

(writing the full specification from this animated picture is left as an exercise for the reader 😂
--------
<details>
    <summary>deep-equal-sequence</summary>
	  <blockquote>
          <details>
				 <summary>deep-equal-item</summary>
					  <blockquote>
	  					  <p>deep-equal-atomic</p>
						  <details>
								<summary>deep-equal-map</summary>
								  <blockquote>
										  <p>deep-equal-atomic</p>
										  <p>deep-equal-sequence</p>
								  </blockquote>
						  </details>
						  <details>
							  <summary>deep-equal-array</summary>
								  <blockquote>
										  <p>deep-equal-sequence</p>
								  </blockquote>
						  </details>
						  <details>
							  <summary>deep-equal-node</summary>
								  <blockquote>
										  <p>deep-equal-document</p>
										  <details>										  
											  <summary>deep-equal-element</summary>
												  <blockquote>
													  <p>deep-equal-attribute</p>
													  <p>deep-equal-NS</p>
													  <p>deep-equal-PI</p>
													  <p>deep-equal-comment</p>
													  <p>deep-equal-text-node</p>
												  </blockquote>
										  </details>										  
										  <p>deep-equal-attribute</p>
										  <p>deep-equal-NS</p>
										  <p>deep-equal-PI</p>
										  <p>deep-equal-comment</p>
										  <p>deep-equal-text-node</p>
								  </blockquote>
						  </details>
					  </blockquote>
		  </details>
	  </blockquote>
  </details>

**Comment by ChristianGruen** [comment]
The divide-and-conquer concept is an interesting analogy, which I’m trying to expand (sorry in advance for all the flaws): If we regard Philip II of Macedon (which seems to be shown in the picture) to be the implementor of the language, I concur: It’s reasonable to assign the type comparisons to the specific implementations of the items instead of assembling them in a single place in the code. If I slip into the shoes (sandals) of Philip’s people (aka the users of the language), I’m not that sure anymore: I possibly want to do nothing else than compare two items, regardless of what they represent. In other words, when having purchased goods in the League of Corinth, I might not have cared in which region of the empire they were produced.

As a side note, I’ve been wondering why “impera” has been translated to “conquer” in English, until I noticed that there also seems to be the translation “divide and rule”. Next, I learned that the origin of the widely quoted phrase appears to be unclear (Macchiavelli is probably the one who has first theorized the concept).

**Comment by rhdunn** [comment]
The options for these would need specifying in a separate section, possibly annotating which apply in what context. -- The rationale for this is that because a user calling deep-equal-sequence, deep-equal-map, etc. may want to specify how node items in those are compared, and those functions will need to forward the options to them.

Therefore, you would have a section structure similar to:
```
Deep Equals
    Deep Equals Options
    Deep Equals for Sequences
    Deep Equals for Atomic Types
    Deep Equals for Maps
    Deep Equals for Arrays
    Deep Equals for Nodes
        Deep Equals for Element Nodes
        Deep Equals for ...
```

Each subsection would also want to reference the relevant options to make it easier for readers/implementers of the specification.

**Comment by rhdunn** [comment]
I don't think anyone here is suggesting passing function-based options for comparison, etc. This is about decomposing the logic into smaller helper functions. For example:
```
(: This is the "deep-equal-sequence" function, no need to add the `-sequence` suffix here, though. :)
declare function fn:deep-equal(
    $input1    as item()*,
    $input2    as item()*,
    $collation as xs:string? := fn:default-collation(),
    $options   as map(*)     := map{}
) as xs:boolean {
    (: fn:zipped here takes 2 sequences and returns the item-wise pairing of the
       item at each position in the sequence. I'm also using array destructuring
       here to simplify the code. :)
    every $[item1, $item2] in fn:zipped($input1, $input2)
    satisfies fn:deep-equal-item($item1, $item2, $collation, $options)
};

declare function fn:deep-equal-item(
    $input1    as item(),
    $input2    as item(),
    $collation as xs:string? := fn:default-collation(),
    $options   as map(*)     := map{}
) as xs:boolean {
    typeswitch ($input1)
    case xs:anyAtomicType return
        fn:deep-equal-atomic($input1, $input2, $collation, $options)
    case map(*) return
        fn:deep-equal-map($input1, $input2, $collation, $options)
    case array(*) return
        fn:deep-equal-array($input1, $input2, $collation, $options)
    case node() return
        fn:deep-equal-node($input1, $input2, $collation, $options)
    default return
        false() (: or raise an error :)
};

(: etc. :)
```

**Comment by ndw** [comment]
If it was convenient in the specification to describe the semantics of `fn:deep-equal` in terms of a selection of subordinate functions, I'd be fine with that. But if the proposal is that we should expose a menu of `fn:deep-equal-*` functions to the user, I think I share @ChristianGruen 's concerns about usability.

I can imagine specialized circumstances where I might know that a function was passed two sequences and I could use `fn:deep-equal-sequences` to compare them, but how would this be a benefit over calling `fn:deep-equal` on them?

And if I don't know what's being passed in, if I've written a library function that might get passed in two `item()` operands, I'm going to want to call `fn:deep-equal` on them (I am absolutely not going to want to construct an elaborate `xsl:choose` or `typeswitch` statement to work out what the arguments are so that I can call the appropriate `fn:deep-equal-*` function!). At that point, I'm going to want to be able to pass some or all of the control operands that are currently proposed, so this selection of functions doesn't seem to be a simplification.

What am I missing?

**Comment by cedporter** [comment]
Following on to @ndw's point, what happens if you call fn:deep-equal-* and supply the incorrect type operands? If this were implemented, is there great efficiency to be gained by using a more specific deep-equal function rather than the existing function if you know your types?

**Comment by ChristianGruen** [comment]
With regards to efficiency, I wouldn’t expect to see any difference between the existing function and the proposed function set.

**Comment by dnovatchev** [comment]
> Therefore, you would have a section structure similar to:
> 
> ```
> Deep Equals
>     Deep Equals Options
>     Deep Equals for Sequences
>     Deep Equals for Atomic Types
>     Deep Equals for Maps
>     Deep Equals for Arrays
>     Deep Equals for Nodes
>         Deep Equals for Element Nodes
>         Deep Equals for ...
> ```

@rhdunn Exactly!

I imagine having all these options provided in one single map-tree, some of whose intermediate nodes  will have the same name as a corresponding **_deep-equal-xxx_** function.
global comparer-options-map
Furthermore, the specification will provide one such **global _comparer-options-map_** that can easily be referenced or used to produce other, similar maps, where just certain subtrees have been replaced.

**Comment by dnovatchev** [comment]
@ndw 


> If it was convenient in the specification to describe the semantics of `fn:deep-equal` in terms of a selection of subordinate functions, I'd be fine with that. But if the proposal is that we should expose a menu of `fn:deep-equal-*` functions to the user, I think I share @ChristianGruen 's concerns about usability.
> ....
> What am I missing?


I think there are different types of users and we do have to care for each type (Diversity!).

This proposal takes notice of the people who, like my wife, love to have a set of instruments that they may have to need to use on any occasion -- an anticipated one or even in quite unexpected circumstances

BTW now we have a good example of being able to implement collapsible multi-list tree structure in pure HTML, therefore, why don't we think about using this to represent the XML  Schema and XPath XDM type hierarchy, as I proposed in the past?

This is definitely a convenient, obvious, self-explanatory, and time-saving way of presentation.

**Comment by dnovatchev** [comment]
> The divide-and-conquer concept is an interesting analogy, which I’m trying to expand (sorry in advance for all the flaws): If we regard Philip II of Macedon (which seems to be shown in the picture) to be the implementor of the language, I concur: It’s reasonable to assign the type comparisons to the specific implementations of the items instead of assembling them in a single place in the code. If I slip into the shoes (sandals) of Philip’s people (aka the users of the language), I’m not that sure anymore: I possibly want to do nothing else than compare two items, regardless of what they represent. In other words, when having purchased goods in the League of Corinth, I might not have cared in which region of the empire they were produced.

@ChristianGruen Unfortunately, even today we have to care which empire produced certain goods. Not all goods are equal even though, for good or for bad, most are Chinese-made ...

And if one has the chance to feel like Alexander the Great, or (for our gentle wives) be able to wear a Christian Dior dress, let us have (give them) that moment. If we leave this slip, then certainly another moment will come in the future, when, looking back, we will definitely regret missing such unique opportunity.

**Comment by dnovatchev** [comment]
@cedporter 

> Following on to @ndw's point, what happens if you call fn:deep-equal-* and supply the incorrect type operands?

In some cases this will cause a compile time (static) error, like passing a comment where an attribute was expected.

In other cases, the effect will be that parameters might be up-casted (say, a map to a sequence) thus the comparison will be the same as comparing two sequences, which I believe would be harmless as this is all we have at present.

**Comment by Arithmeticus** [comment]
In the original post, there should be an intermediate function, `deep-equal-map-member()` or some-such, between `deep-equal-map()` and its two children functions, because the results of the last two items need to be coordinated pairwise in map key-value pairs.

**Comment by dnovatchev** [comment]
@Arithmeticus  Thanks for pointing this out!

Actually, I mentioned 7 days ago that we need **`set-equals()`** when comparing the attributes of two elements, the keys of two maps, the unorderd (xs:all) children.

**Comment by michaelhkay** [comment]
This has been an interesting discussion about the design principles we apply when designing features, but I don't think it identifies a concrete actionable change to the specification; I'd suggest that any concrete changes arising from the discussion would be better handled in separate issues, and that there is little point in keeping this one open.

**Comment by ndw** [comment]
At [meeting 039](https://qt4cg.org/meeting/minutes/2023/06-20.html#open-pull-requests) the CG agreed to close this issue without further action.
