### ISSUE TITLE
[XPath] [XQuery] Better names for ThinArrowTarget and FatArrowTarget

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#4]
The `ThinArrowTarget` and `FatArrowTarget` EBNF symbols do not follow the convention in the XPath and XQuery specifications of describing the semantics of the symbols, but instead describe how they are written.

I propose the following names:
1. `CurryingArrowTarget` instead of `FatArrowTarget` -- This is because the LHS is being curried into the function, making the function call it applies to take one less parameter. Other possible names would be `SimpleArrowTarget` or `UnaryArrowTarget`.
1. `MappingArrowTarget` instead of `ThinArrowTarget` -- This is because both variants make use of the simple map operator.

**Comment by michaelhkay** [comment]
I guess "Arrow Expressions" in 3.1 was the thin end of a wedge, then!

The names used in the EBNF are at one level arbitrary, but the names used in the spec prose, such as "Arrow Expressions" aren't. If the names aren't appealing and memorable to users, it becomes very hard to design error messages; a classic example is the `TransformExpr` in XQuery Update 1.0, referred to in the spec as a "transform expression", but it doesn't use the keyword "transform" in the syntax, (it uses copy/modify), so it's likely that an error message referring to a "transform expression" would be somewhat bewildering. So I think it's important to choose names that will mean something to the typical user, and from that perspective I think I prefer my proposed names.

**Comment by rhdunn** [comment]
Thanks for the explanation. I'm closing this now.

**Comment by graydon2014** [comment]
From a "I remember what this looks like, what is its real name and where is it defined?" perspective, "fat arrow" -- even "broad arrow" -- and "thin arrow" strike me as not being optimal choices of names.  (The use of `?` with maps and arrays is a helpful bit of syntax but it's not easy to find where it's defined or what it's really called.  I'm hopeful for less of that.)

"fat arrow" is used in Javascript for something else, but with the same `=>` symbol; it's going to dominate the search results.  "arrow operator", for `->`, is a C/C++ symbol and will dominate search results for the symbol. Searching for the syntax isn't likely to work.

"Reducing arrow" and "mapping arrow" won't work because the simple mapping operator already exists and the present thin arrow would have to be the _function mapping operator_.

_reducing arrow_ and _iteration arrow_ are the least awful names I can devise.   Perhaps "substitution arrow" for `=>` instead?

**Comment by ChristianGruen** [comment]
Related to that, we could try to find a catchy term for function item expressions (introduced by `->` ) that allow values to be bound as context item.

@rhdunn Maybe it’s worth reopening the issue?

**Comment by michaelhkay** [comment]
In thinking of names for constructs, the question I like to ask myself is "how will we describe it in an error message?".

From that perspective, the "transform expression" in XQuery Update was disastrous. No-one who has written "copy ... modify ... return" is going to relate to an error message that calls it a "transform expression".

Of course with a symbolic operator, the error message can always quote the symbol: "Error in '->' expression".

But I'm confortable with "thin arrow" and "thick arrow", just as we have "square" and "curly" array constructors.

Michael Kay

**Comment by graydon2014** [comment]
I think effective error messages are important, but I also think people have to use the construct to get to the possibility of the error message.  Being able to talk about any particular construct with specific language helps.

**Comment by ChristianGruen** [comment]
In #447, Michael Kay renamed the operators as follows:

• **sequence arrow**: `=>`
• **mapping arrow**: `=!>` (before: `->`)

The current plan is to use the thin arrow `->` exclusively for the new compact syntax of anonymous functions.

I believe we can close this issue once the pull request is accepted.

**Comment by joewiz** [comment]
I like `=!>` - it has a good mnemonic association with `!` and `=>`.

**Comment by ChristianGruen** [comment]
Closed (further discussion: #53, #435, #436 et al.)
