### ISSUE TITLE
Converting doubles to decimals, fractional digits

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#410]
Adopted from a previous discussion on Slack: The result of the following computation…

```xquery
<x>2</x> + .1
```

…is serialized as `2.1`. If the result is cast to a decimal via `xs:decimal(<x>2</x> + .1)`, `2.100000000000000088817841970012523233890533447265625` is returned, which feels counterintuitive.

Can we possibly change the conversion rules without compromising backward-compatibility?

**Comment by michaelhkay** [comment]
I've just been exploring the history of this.

for double-to-string, XPath 1.0 required "there must be as many, but only as many, more digits as are needed to uniquely distinguish the number from all other IEEE 754 numeric values". In 2.0 this was relaxed so you could produce any string you liked that round-tripped back to the original double.

for double-to-decimal it seems the requirement has always been to generate the exact decimal, rather than any decimal you liked that round-tripped back to the original double.

It does seem hard to defend this. (a) because it's inconsistent, and (b) because the precision you get with double-to-decimal conversion is entirely spurious.

But I'm worried about compatibility. Some people do things where numeric precision really matters.

We've changed the rules for equality comparison of mixed numeric types so a double and decimal are now compared by converting the double to an exact decimal. Changing the conversion rules so a double converts to an approximate decimal would seem like a step in the opposite direction.

**Comment by ChristianGruen** [comment]
Thanks for the assessment, Michael.

> We've changed the rules for equality comparison of mixed numeric types so a double and decimal are now compared by converting the double to an exact decimal.

Do I remember correctly/am I right to assume that the following comparison…

```xquery
<x>2</x> + .1 = 2.1
```

…won’t yield `true` in the future?

Wouldn’t that be inconsistent/surprising as well – even more if `<x>2</x> + .1` is serialized as `2.1` – and how could we tackle that?

**Comment by michaelhkay** [comment]
`<x>2</x> + .1 = 2.1` - Yes I think you're right that the result changes in 4.0 -- and some people are going to trip over this.

There would be an argument for taking the change further and making all mixed-numeric operations work in infinite-precision decimal space, including untyped-atomic to numeric conversion. Whether that would only make the disruption worse is hard to foresee. Perhaps it should all be controlled by a run-time evaluation mode?

**Comment by michaelhkay** [comment]
The rationale was to get rid of the non-transitivity of the comparison used in `distinct-values()` and xsl:for-each-group.

Another approach to the problem would be to change those functions to use `atomic-equal()` [formerly op:same-key()] instead of using `eq`.

**Comment by ChristianGruen** [comment]
Using `atomic-equal()` sounds like a good compromise to me. It could be less intrusive than changing the general comparison semantics.

**Comment by michaelhkay** [comment]
Unfortunately a simple switch to atomic-equal() in distinct-values() would have other consequences, for example it would affect the comparison of dates/times with and without timezones.

And parameterizing distinct-values() with a comparison function isn't such a good idea as it seems, because an efficient implementation needs to compute a hashcode. (Also, a user-supplied comparison function might not be transitive).

We could however change distinct-values to use a custom equality function of its own - yet another equality operator.

**Comment by ChristianGruen** [comment]
One of our users was surprised to see that the following query now returns `false` instead of `true` in our latest release (which already supports the new rules for equality comparison of mixed numeric types):

```xquery
let $n := 0.3
return $n = xs:double($n)
```

I really think we should switch back to the original behavior and find another solution for `fn:distinct-values`.

**Comment by ChristianGruen** [comment]
@michaelhkay I wanted to revert some edits in [4.3 Comparison operators on numeric values](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#comp.numeric) and related paragraphs, and I found that the changes were added in one large commit aaec281b729f3126374c11587157eef57837c8c5 (Message: Commit all initial 4.0 work). Can you remember if there’s a single commit available, somewhere in a different repository, that only includes the changes related to this issue?

**Comment by michaelhkay** [comment]
Almost certainly not, I'm afraid. I hadn't yet adjusted to the GIT-based approach of editing in small self-contained increments.

**Comment by ChristianGruen** [comment]
Related (we decided to keep it that way): https://stackoverflow.com/questions/76259454/type-casting-issue-in-xquery

**Comment by michaelhkay** [comment]
Where have we got to on the original issue?

I'm opposed to changing the behaviour of `xs:decimal(xs:double)` for compatibility reasons. But perhaps there is something else we might do? A function that has the effect of `xs:decimal(xs:string(xs:double))` perhaps, or one that combines double-to-decimal conversion with rounding?

If not, we should close the issue with a "no action" outcome.

**Comment by ChristianGruen** [comment]
> Where have we got to on the original issue?

Our consideration of preserving the current conversion rules sounds reasonable to me; a change would be too invasive. I’ve just added the StackOverflow link for the record.

As for the discussion that follows, I think we should only close the issue after we have resolved https://github.com/qt4cg/qtspecs/pull/455.
