### ISSUE TITLE
Make sure the build system syntax checks the syntax of examples

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#421]
Apparently the code is lying around somewhere...

**Comment by ChristianGruen** [comment]
I assume this is related to https://github.com/qt4cg/qtspecs/pull/465#issuecomment-1535086474 ?

**Comment by michaelhkay** [comment]
There are several parts to this.

For functions and operators, we have a stylesheet generate-qt3-test-set.xsl that can be applied to the function catalog to generate the test set `fo-spec-examples.xml`. It's probably best to run this occasionally rather than integrating it into the build, because tests will generally fail until the functions have actually been implemented.

For the XSLT spec, `<eg>` elements can be annotated with `role="stylesheet"`, `role="declaration"`, or `role="instruction"`. This was used in 3.0 for syntax highlighting but this appears not to be working in the 4.0 build (see for example §10.3.9 Examples of Stylesheet Functions. The markup has also been used in the past for syntax checking. There is a stylesheet `example-checker.xsl` to achieve this: I'm not sure if we are currently running it. And of course, there are a lot of new examples that should use this markup but don't do so.

For XPath/XQuery there is a similar markup `<code role="parse-test">...</code>` - I assume the idea is that the code must contain a valid XPath (or XQuery?) expression. I'm not sure what mechanism is (or has been) used to actually check the syntax.

**Comment by michaelhkay** [comment]
I've done an ad-hoc run of the `example-checker.xsl` stylesheet and it works, though the output is very untidy and hard to interpret. It would be useful to change to call `fn:transform` rather than `saxon:comple-stylesheet`, though `fn:transform` does not have a "syntax-checking-only" mode, we can probably work around that. More difficult is to capture any errors that arise.

**Comment by michaelhkay** [comment]
I've attempted to add a rule to xsl-query-2016.xsl that calls xsl:evaluate to check examples annotated with `role="parse-test"`. It's hampered by the fact that (a) many of these examples are XQuery rather than XPath, (b) many of the examples have context dependencies, (c) xsl:evaluate reduces all static errors to XTDE3160, so we can't distinguish "invalid grammar" from "undeclared variable".

**Comment by michaelhkay** [comment]
Another problem is that the example in the spec might be correct, but might use syntax that is not yet implemented in the XSLT processor used for the build. It's probably not a good idea for the build to use the latest snapshot of the XSLT implementation.

**Comment by michaelhkay** [comment]
I haven't identified anything that can be usefully done at low cost, so I'm going to propose closing with no action.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 099](https://qt4cg.org/meeting/minutes/2024/11-19.html).
