### ISSUE TITLE
Allow type promotion of xs:string to xs:anyURI

### ISSUE THREAD

**Issue by joewiz** [qt4cg/qtspecs#480]
If it hasn't already been considered and ruled out, I'd like to propose adding a type promotion rule to XPath 4 that would allow `xs:string` to be type-promoted to `xs:anyURI`, so that functions with parameters whose types are declared as `xs:anyURI` can directly take `xs:string` values, without having to first cast these to `xs:anyURI`. 

This would empower function authors to select `xs:anyURI` as a type - signaling that they’re expecting a URI - without forcing users of the function into explicitly casting their string-typed URIs.

The motivation behind this proposal is that many eXist users are frustrated when using the eXist extension functions that properly declare parameters as `xs:anyURI`. If this proposal isn’t adopted, that’s ok; we’ll just eliminate the use of `xs:anyURI` in our functions, as proposed in https://github.com/eXist-db/exist/issues/4632. But this would a bit unfortunate for authors of functions who see the use of `xs:anyURI` as a proper expression of intent in their functions.

The change would be to https://www.w3.org/TR/xpath-31/#promotion - and I guess would be a 3rd item, called "String type promotion", saying:

> A value of type `xs:string` can be promoted to the type `xs:anyURI`. The result of this promotion is created by casting the original value to the type `xs:anyURI`.

**Comment by michaelhkay** [comment]
In the standard function library we solved this problem by avoiding use of xs:anyURI as an argument type.

The term "promotion" perhaps needs to be changed if we do this, since promotion suggests some kind of ranking. Perhaps it's only the choice of terminology that makes me uneasy. I can't think of any immediate problems that would arise, any more than there would be problems in allowing mutual implicit casting between xs:hexBinary and xs:base64Binary - which would benefit anyone using the EXPath binary library.

We do still have residual text that suggests implementations are allowed to impose restrictions on the content of a valid xs:anyURI. We either need to find and remove that text, or to define what happens when the implicit casting fails.

**Comment by joewiz** [comment]
Regarding "text that suggests implementations are allowed to impose restrictions on the content of a valid xs:anyURI," I do see some language to this effect in https://www.w3.org/TR/xmlschema-2/#anyURI:

> Because it is impractical for processors to check that a value is a context-appropriate URI reference, this specification follows the lead of [RFC 2396] (as amended by [RFC 2732]) in this matter: such rules and restrictions are not part of type validity and are not checked by ·minimally conforming· processors. Thus in practice the above definition imposes only very modest obligations on ·minimally conforming· processors.

I scanned through the 15 instances of xs:anyURI in https://www.w3.org/TR/xpath-31/ and 22 in https://qt4cg.org/specifications/xquery-40/xpath-40.html and couldn't see any language that sounded like special restrictions, but perhaps a more knowledgable reader would spot phrases that implied restrictions.

**Comment by michaelhkay** [comment]
See the last paragraph of §2.6 in the XDM data model spec; and the third para of §2.7.3.

And in F+O §21.2 we say "For xs:anyURI, the extent to which an implementation validates the lexical form of xs:anyURI is [·implementation-dependent·]"

**Comment by michaelhkay** [comment]
It's complicated by the fact that namespaces are supposed to be URIs; and there are some libraries (such as XOM) that actually insist that namespaces are valid URIs in some sense of the term. The namespaces REC is incredibly frustrating in this regard because it makes several statements that appear contradictory:

- An XML namespace is identified by an IRI reference [[RFC3987]](https://www.w3.org/TR/xml-names11/#IRIRef)
- The use of relative IRI references, including same-document references, in namespace declarations is deprecated.
- The rules for document conformance and wellformedness place no constraints on what strings may be used as namespaces

As a result the QT specifications are ambivalent about what strings may be used as namespaces. For example, for namespace constructors in XQuery the spec says "An implementation MAY raise a [dynamic error] [[err:XQDY0074] if the URIExpr of a computed namespace constructor is not a valid instance of xs:anyURI."

Another complication is that it's very hard to find any definitive statements about whitespace in namespace names. Apart from the statement in the namespaces REC that namespace names are IRI references (but the document is still conformant if they aren't), the only thing it says is that they are subject to XML attribute value normalization (which replaces newlines and tabs by single spaces). In practice if you try to use spaces in namespace names then a lot of things are going to break: but one thing that probably won't break is the XML parser.

So the whole area is a bit of a minefield.

**Comment by ndw** [comment]
At [meeting 035](https://qt4cg.org/meeting/minutes/2023/05-23.html) the CG agreed to try this. Action on NW to draft a PR to implement it.

**Comment by ChristianGruen** [comment]
I wonder what is going to happen if the type of a function parameter is `union(xs:string, xs:anyURI)`?

Presumably, an `xs:anyURI` argument would be converted to `xs:string` because `xs:string` is placed first in the list of allowed types?

**Comment by ChristianGruen** [comment]
Tackled by #815. Do we want to close it?

**Comment by ndw** [comment]
Yup. Thanks.

**Comment by joewiz** [comment]
@michaelhkay @ndw @ChristianGruen Thank you so much!
