### ISSUE TITLE
When we have array:build and map:build, then why do we also need array:of and map:of ?

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#481]
Looking at the current specification of the pairs of functions: (**_[array:build](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-array-build)_**, **_[array:of](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-array-of)_**) and (**_[map:build](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-map-build)_**, **_[map:of](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-map-of)_**), it is impossible not to notice that the second function in each of these pairs is a weak duplicate of the first.

Also, the examples provided for **_array:build_** and **_array:of_**, seem to have a good deal of common content / duplication / overlap.

Another issue is that **_array:of_** requires as input a sequence of  **value records**, whose definition is challenging to understand (and whose meaning seems to be solely to represent a sequence of sequences), and what is also really challenging is how to construct this argument to **_array:of_**. If this is unnatural and challenging, one would probably prefer to use just **_array:build_**.

Is there an example where it is possible to construct an array (or a map) with **_array:of_** (or with **_map:of_**) but it is impossible (or significantly more difficult) to construct the same array/map with the function **_array:build_** (or with **_map:build_**)? 

If there are no such significant and convincing examples, then why do we need the **_xxx:of_** functions?

Thus the question naturally arises:  "**_Why is the function `xxx:of` necessary at all?_**"

**Comment by michaelhkay** [comment]
Good question. `array:of(X)` is just `array:build(X, function($x){$x?value}), with stronger typing on the type of the first argument. The reason for having it is that it provides an inverse to `array:members()` - you can decompose an array into "value records", manipulate the value records, and then reconstruct a new array. To do that with array:build you need to understand the internal structure of a "value record"; but perhaps you need to do that anyway.

Similarly, `map:of(X)` is just `map:build(X, function($pair){$pair?key, $pair?value})`, again with stronger typing, and the reason for having it is that it provides an inverse to `map:pairs()`.

These are convenience functions, and it's valid to raise the question whether the convenience they offer is sufficient to justify including these functions in the library. Personally I think it probably is -- mainly because of the extra type checking, which gives improved diagnostics -- but it's a value judgement.

**Comment by ndw** [comment]
We agreed to close this issue with no action at [meeting 034, 16 May 2023](https://qt4cg.org/meeting/minutes/2023/05-16.html)
