### ISSUE TITLE
New Map & Array Functions: Inconsistencies

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#508]
### XQFO 3.1

…provides the following functions/constructs for creating and accessing maps & arrays:

Maps | Singleton Maps
:--- | :---
Decompose | –
Compose | `map:merge($maps)`
Create single | `map:entry($key, $value)`<br>`map { $key: $value }`
Extract keys | `map:keys($map)`
Extract values (flat) | `$map?*`
**Arrays** | **Singleton Arrays**
Decompose | –
Compose | `array:join($arrays)`
Create single | `[ $value ]`
Extract values (flat) | –

### XQFO 4.0 Draft

…provides new functions for singletons and map representations:

Maps | Singleton Maps | Pairs (Key-Value Pair Maps)
:--- | :--- | :---
Decompose | **`map:entries($map)`** | **`map:pairs($map)`**
Compose | `map:merge($maps)` | **`map:of($pairs)`**
Create single | `map:entry($key, $value)`<br>`map { $key: $value }` | –<br>**`map { 'key': $key, 'value': $value }`**
Extract keys | `map:keys($map)` | **`$pairs?key`**
Extract values (flat) | **`map:values($map)`**<br>`$map?*` | **`$pairs?value`**
**Arrays** | **Singleton Arrays** | **Members (Value Maps)**
Decompose | – | **`array:members($array)`**
Compose | `array:join($arrays)` | **`array:of($members)`**
Create single | `[ $value ]` | **`array { 'value': $value }`**
Extract values (flat) | **`array:values($array)`** | **`$members?value`**

The following terminology can be derived from the function names:

* A key-value pair map with a single map pair is called a **Pair**.
* A value map with a single array member is called a **Member**.
* A singleton map is called an **Entry** (due to `map:entry`) 
* We have no name for a singleton array.

### Complete the Picture

I believe we should:

1. rename `map:of` to `map:of-pairs` or `map:merge-pairs` (as a hint that singletons are not the expected input)
2. rename `array:of` to `array:of-members` or `array:join-members` (as a hint…)
3. add `map:pair` for creating a single pair
4. add `array:split` (`array:tokenize`, …?) for decomposing arrays to singleton arrays

I’m not sure if we should add array functions for creating singletons or value maps; we also have `array:build`.

**Comment by dnovatchev** [comment]
> 4\. add `array:split` (`array:tokenize`, …?) for decomposing arrays to singleton arrays

I already raised an issue that the existing 3.1 **[fn:array:flatten](https://www.w3.org/TR/xpath-functions-31/#func-array-flatten)** should not return a sequence, but an array.

Maybe we just need to improve **[fn:array:flatten](https://www.w3.org/TR/xpath-functions-31/#func-array-flatten)**?

One example could be to give it a second parameter that is the desired depth of flattening.

**Comment by michaelhkay** [comment]
I've never found any use for `array:flatten()` but we can't make incompatible changes to functions just because we don't like them. If the function were seriously harmful then we could consider deprecating it. But this function is harmless, just ignore its existence.

**Comment by dnovatchev** [comment]
> If the function were seriously harmful then we could consider deprecating it. **But this function is harmless, just ignore its existence**.

@michaelhkay 
Can I quote you outside of github? 😃 

More seriously, we could actually fix it, if we want.

**Comment by michaelhkay** [comment]
If you can find a way of improving it that doesn't break existing applications, please make your proposal.

**Comment by dnovatchev** [comment]
> If you can find a way of improving it that doesn't break existing applications, please make your proposal.

One obvious way is to add a new parameter, say **`return-array-sequence := false()`**

If  in a particular function call the value of this argument is `true()` then the result must be a sequence of arrays,  each one of these having as its single member a corresponding leaf-member of the original array.

In other words:

**`array:flatten($ar, return-array := true())`** can be implemented with the following XPath code:

```xq

let $result := [],
   $flattenBase := function($ar as array(*), $res as array(*), $self as function(*))
  {
    let $extractMember := function($mem as item()*)
       {
         if(not($mem instance of array(*)))
           then array:append($res, $mem)
           else $self($mem, $res, $self)
       }
       return
          array:for-each($ar, $extractMember)
   },
   $flatten := function($ar as array(*))
    { $flattenBase($ar, $result, $flattenBase) }
  return
    $flatten([1, (2, 3), 5, (), 7, [8, [10, 11, 12], (), 9]]) 
```

As written above, with BaseX this evaluates to:

**`[ [1], [(2,3)],  [5],  [()],  [7],  [  [8],  [ [10], [11], [12] ], [()], [9]  ]  ]`**

In order to return a sequence of arrays as the result and get rid of the outermost-encompassing array, we need to use `array:members` (and not `array:for-each`), but BaseX doesn't implement yet `array:members`, thus I am not able to write t his code at present.

When writing and evaluating the correct code that uses `array:members`,  the correct result will be produced:

**` [1], [(2,3)],  [5],  [()],  [7],    [8],   [10], [11], [12], [()], [9] `**

**Comment by dnovatchev** [comment]
Or we, indeed, could have a separate new function for this:

**_array:leaf-members_**

But I personally would prefer to have only one, single function, as outlined in my previous comment.

**Comment by ChristianGruen** [comment]
> > 4. add `array:split` (`array:tokenize`, …?) for decomposing arrays to singleton arrays
>
> I already raised an issue that the existing 3.1 **[fn:array:flatten](https://www.w3.org/TR/xpath-functions-31/#func-array-flatten)** should not return a sequence, but an array.

This may be a different requirement. I was asking for a function that returns a sequence of singleton arrays. The counterparts of `join` functions are often called `split` or `tokenize`:

#### First example

```xquery
(: Return value of array members in elements :)
array:split([ (), 1, (2, 3) ]) ! element node { . }

(: The result :)
<node/>
<node>1</node>
<node>2 3</node>
```

#### Second example

```xquery
(: Return new array with absolute numeric values. :)
let $array := array { -1 to 1 }
let $tokens := array:tokenize($array)
let $updated := (
  for $token in $tokens
  return [ abs($token) ]
)
return array:join($updated)

(: One-liner version :)
array:join(array:tokenize(array { -1 to 1 }) ! [ abs(.) ])

(: The result :)
[ 1, 0, 1 ]
```

In the future, it will be possible to do…

```xquery
array:members($array) ! element node { ?value }

(: …and one of… :)

array:build(array:members($array) ! abs(?value))
array:join (array:members($array) ! array { abs(?value) })
array:of   (array:members($array) ! map { 'value': ?value })
``` 

…or, with FLWOR expressions…

```xquery
for member $member in $array
return element node { $member }

(: …and… :)

array:build(
  for member $member in $array
  return abs($member)
)
``` 

…but I can imagine that people who are used to `array:join` may want a simple and unobtrusive reverse function.

**Comment by ndw** [comment]
A quick search of the DocBook xslTNG stylesheets reveals almost 10 uses of `array:flatten()` to turn an array into a sequence that I can interate over. I guess I could iterate over the array with an index, but that doesn't seem easier or better to me than turning it into a sequence. Or am I missing something?

**Comment by dnovatchev** [comment]
**Update**:

Here is a correct implementation of the extension of **fn:array:flatten** when in the function call the value of the parameter **_`return-array-sequence`_**  is **`true()`** . This is a pure XPath 3.1 implementation:

```xq
let $result := [],
   $flattenBase := function($ar as array(*), $res as array(*), $self as function(*))
  {
    let $extractMember := function($mem as item()*)
       {
         if(not($mem instance of array(*)))
           then array:append($res, $mem)
           else $self($mem, $res, $self)
       }
       return
         for $i in 1 to array:size($ar)
           return
             $extractMember($ar($i))
          
   },
   $flatten := function($ar as array(*))
    { $flattenBase($ar, $result, $flattenBase) }
  return 
  $flatten([1, (2, 3), 5, (), 7, [8, [10, 11, 12], (), 9]]) 
```

The correct result (a sequence of arrays, each containing the next leaf-level member) is produced with BaseX :

```
[1]
[(2,3)]
[5]
[()]
[7]
[8]
[10]
[11]
[12]
[()]
[9]
```

**Comment by dnovatchev** [comment]
@ChristianGruen , @ndw 

1. The flaw of **[array:flatten](https://www.w3.org/TR/xpath-functions-31/#func-array-flatten)** as defined in FO 3.1 is that **it returns a sequence of the leaf-level members**. This unfortunately isn't lossless. If any member is the empty sequence, any such member is not returned (lost) because one cannot have the empty sequence appear as an item in a sequence.

2. The proposed and implemented fix is having a new boolean parameter **_return-array-sequence_**  with default value `false()` . The fixed functionality is only performed in function calls where this parameter is set to `true()`. This guarantees backwards compatibility, because until yesterday no one was aware of the new argument (and it didn't exist)...

3. The fixed function, when called with **`return-array-sequence := true()`** does not lose any leaf-level member. The result is now not just a sequence, but a sequence of arrays, each containing a single, leaf-level member of the array. Thus, if such member was the empty sequence, now it is not lost, but is in an array-item in the result, with value **`[()]`**.

4. The difference between **`array:flatten`** and the proposed `array:split` and/or `array:tokenize` is that the latter returns the members of the array at the top level of nesting, but **`array:flatten`** returns all members that are leaves, and does not preserve any hierarchy.

5.  We don't need to count the number of times **`array:flatten`** was used in any existing codebase, because, as explained above, all existing calls to **`array:flatten`** will continue to produce the same result. **Backwards compatibility is not affected**.

**Comment by dnovatchev** [comment]
> I agree that `array:flatten` could be used equivalently to `array:split` if the array members are single items, as it’s the case in my second example:

@ChristianGruen You haven't specified this function, so I am just guessing that they could  be equivalent if the proposed `array:split`  loses any member with value the empty sequence, as `array:flatten` currently does.

If however `array:split` preserves such members, then these two functions are not equivalent even in the case when "the array members are single items"

**Comment by dnovatchev** [comment]
> `array:split($array)` would be equivalent to:
> 
> ```xq
> array:for-each($array, function($m) { [ $m ] })
> ```
> 
> If `$a` is an array, `deep-equal($a, array:join(array:split($a)))` is expected to return `true`.
> 
> Hope this helps.

Thanks, this helps and definitely means that `array:split` cannot be equivalent to the existing [`fn:array:flatten`](https://www.w3.org/TR/xpath-functions-31/#func-array-flatten), because the latter returns a sequence of items, but from the description above, `array:split`  must return a single array, as does **[`fn:array:for-each`](https://www.w3.org/TR/xpath-functions-31/#func-array-for-each)**.

**Comment by ChristianGruen** [comment]
Sigh, I should run queries before I post. There’s a reason why `array:for-each` was designed to return an array and not a sequence (like `map:for-each`), but it frequently sends me in the wrong direction.

For the result to be reversible with `array:join`, it needs of course be:

```xquery
for $i in 1 to array:size($array)
return [ $array($i) ]
```
