### ISSUE TITLE
fn:parse-uri, fn:build-uri: Feedback

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#566]
Feedback on `fn:parse-uri` (thanks, @ndw, for the comprehensible rules in the spec):

1. With the current rules, the port is not detected in `http://x:80`. Maybe `x:` is misinterpreted as the beginning of a Windows path?
2. The *uri decoding* should be revised. It’s currently possible to create strings with invalid Unicode characters: `parse-uri('%FF')`. With the current rules, the following expression returns `df83` and `dc00`:

```xquery
parse-uri('%FF00')
=!> map:get('filepath')
=!> string-to-codepoints()
=!> format-integer('16^XX')
```

More to come (or not).

**Comment by ChristianGruen** [comment]
3. Most regex strings ends with a dollar sign, but only some of them start with a circumflex character. Maybe it’s better to use `^` everywhere?

4. I believe that either the test cases or the specification needs to be aligned. The `path` in the test result often starts with a slash `/`, e.g. in [fn-parse-uri-016](https://github.com/qt4cg/qt4tests/blob/70b0839940503210421fbe43fd4e0b6363249e18/fn/parse-uri.xml#L305-L319). According to the rules, leading slashes are removed:
    * If the *string* matches `^[a-zA-Z][:|].*$`: […] a leading slash `/` is added to the *string*.
    * …
    * If the *string* matches `^//*([a-zA-Z]:.*)$`, the *authority* is empty and the *string* is the first match group.
    * …
    * If the *string* is the empty string, then *path* is the empty sequence, otherwise path is the whole *string*.

**Comment by ChristianGruen** [comment]
I noticed that the rules for `fn:build-uri` include invocations of `fn:encode-for-uri`.

The initial suggestion in #72 was to provide a function for decoding a URI. Maybe we should still think about adding a `fn:decode-uri` or `fn:decode-from-uri` function, in which we could tackle the open issues that need to be solved for 2. The URI decoding rules for `fn:parse-uri` could then be replaced with a reference to the new function.

**Comment by ChristianGruen** [comment]
5. I would prefer to have redundant data removed from the result of `fn:parse-uri`. Otherwise it will be difficult for the user to understand which information is needed to construct URIs via `fn:build-uri` (without reading the spec in full detail). In particular, I find `uri` confusing because it’s a simple copy of the input string.

6. The result of simple URIs feels overly complex to me. I still believe it would be less idiosyncratic/unorthodox if `path-segments` and `query-segments` were returned as plain sequences, and if `query-segments` was a single map with combined values for duplicate keys. If a user really needs query parameters in the original order (which is believe is a pretty rare), it’s still possible to parse them manually. An example:

```xquery
map {
  'path-segments': [ 'data', 'ids' ]
  'query-segments': [
    map { 'key': 'id', 'value': '1' },
    map { 'key': 'id', 'value': '2' },
    map { 'key': 'id', 'value': '3' }
  ]
}

(: This one should be much easier to process :)
map {
  'path-segments': ( 'data', 'ids' )
  'query-segments': map { 'key': 'id', 'value': ('1', '2', '3') }
}
```

7. Feedback on `fn:build-uri`: The two paragraphs starting with “If the `scheme` key is present” and “If the scheme is `file`” should be combined. Otherwise, one might assume that the rules from the second paragraph also apply if there is no `scheme` value.

8. The spec states that “which schemes are known to be non-hierarchical is ·implementation-defined·”. In the tests, however, various schemes are assumed to be known as non-hierarchical (`tel`, `tag`, `mailto`, `news`, `urn`, `jar`, maybe others). Maybe we can include some of them in the specification and drop tests with undefined schemes.

9. `fn:encode-for-uri` is applied on the members of the `path-segments` array, but in various tests, the path segments are adopted unchanged in the results. Maybe a rule is missing to restrict the encoding to specific cases/schemes/whatever?

Segment | Encoded
--- | ---
`a b` | `a%20b`
`c:` | `c%3A`
`John.Doe@example.com` | `John.Doe%40example.com`
`+1-816-555-1212` | `%2B1-816-555-1212`
`Dürst` | `D%C3%BCrst`

**Comment by ndw** [comment]
>  With the current rules, the port is not detected in http://x:80. Maybe x: is misinterpreted as the beginning of a Windows path?

Indeed, the clause `If the string matches ^//*([a-zA-Z]:.*)$` should only apply if the scheme is unknown or is known to be `file`.

**Comment by ndw** [comment]
> The uri decoding should be revised. It’s currently possible to create strings with invalid Unicode characters: parse-uri('%FF'). With the current rules, the following expression returns df83 and dc00:

I think the practical thing to do here is to say that if the resulting sequence of characters is not a valid UTF-8 sequence of characters, any invalid characters are replaced by 0xFFFD. That seems most consistent with replacing %HI with 0xFFFD.

**Comment by ndw** [comment]
> Most regex strings ends with a dollar sign, but only some of them start with a circumflex character. Maybe it’s better to use ^ everywhere?

Yes, I think that was just sloppiness on my part.

>  I believe that either the test cases or the specification needs to be aligned. The path in the test result often starts with a slash /, e.g. in [fn-parse-uri-016](https://github.com/qt4cg/qt4tests/blob/70b0839940503210421fbe43fd4e0b6363249e18/fn/parse-uri.xml#L305-L319). According to the rules, leading slashes are removed:

Yes, I think 016 is wrong.

**Comment by ChristianGruen** [comment]
@ndw I’m not sure how/if the paragraph that have recently been added…

https://github.com/qt4cg/qtspecs/pull/597/files#diff-7625c07ae8131ff65c3caa677b188ed2b9b66237312d11c05a2fa2838c6f5c67R24705-R24714

…are supposed to solve the discussed challenges with the file scheme. The new paragraph seems to be identical to the subsequent paragraph, except for the introducing scheme conditions (not known, or `file`). Next, it’s not clear how to guess the precedence of the rules. It could be…

* `(`no-scheme or file-scheme`)` and string = …regex… or/otherwise …
* no-scheme or `(`file-scheme and string = …regex… `)` ... or/otherwise …
* no-scheme or `(` `(`file-scheme and string = …regex… `)` ... or/otherwise`)` …

I implemented different variants, but I couldn’t guess which one is the one to pursue.

Have the results of the test cases been formulated manually, or does an implementation exist that could serve as inspiration for other implementations?

**Comment by ChristianGruen** [comment]
By the way, I noticed that the changes from the merged PR…

https://github.com/qt4cg/qtspecs/blame/master/specifications/xpath-functions-40/src/function-catalog.xml#L24713

…are not visible in the current draft: https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-parse-uri

I also assume my observation will be outdated soon.

**Comment by ChristianGruen** [comment]
@ndw Now that `fn:decode-from-uri` is available, you could add a reference to that function in the rules of `fn:parse-uri`.

**Comment by ndw** [comment]
Thank you. Yes. Let me see about that.

**Comment by ndw** [comment]
I can't explain why the status quo drafts don't reflect that merge. That's a little scary.

**Comment by ChristianGruen** [comment]
@ndw I guess you’re still in the middle of working my comments up. Just in case, I’ve assembled all tests cases for which I believe there’s still a mismatch between the specification and the test suite:

* [fn-build-uri.txt](https://github.com/qt4cg/qtspecs/files/12642321/fn-build-uri.txt)
* [fn-parse-uri.txt](https://github.com/qt4cg/qtspecs/files/12642336/fn-parse-uri.txt)

Two examples:

```
fn-build-uri-from-parse-023
fn:build-uri(map { "uri": "tel:+1-816-555-1212", "scheme": "tel", "path": "+1-816-555-1212", "path-segments": "+1-816-555-1212" })
Result: tel://%2B1-816-555-1212
Expect: "tel:+1-816-555-1212"

fn-parse-uri-036
fn:parse-uri(`https://example.com:8080/path?s=%22hello world%22&sort=relevance`)
Result: map { "port": "8080", "authority": "example.com:8080", "path": "/path", "scheme": "https", "path-segments": ("", "path"), "query": "s=%22hello world%22&amp;sort=relevance", "host": "example.com", "hierarchical": true(), "uri": "https://example.com:8080/path?s=%22hello world%22&amp;sort=relevance", "query-parameters": map { "s": "%22hello world%22", "sort": "relevance" } }
Expect: [XPST0003] Invalid entity: '&sort=relevance", ...'.
```

"Result" is what’s output by our processor; "Expect" is what the test case expects. "Invalid entity" indicates that something in the test case needs to be properly escaped.

I’ve included all changes from #692 and #696. It could very well be that our implementation is buggy; I appreciate any feedback.

**Comment by ndw** [comment]
The `tel:` scheme is non-hierarchical and has an explicit leading plus, see [RFC 3966](https://www.ietf.org/rfc/rfc3966.txt). We don't mandate what non-hierarchical schemes are implemented so I think you could exclude that test if you wanted to. Or we could remove it, if you'd prefer.

For `fn-parse-uri-036`, I think you're handling the `&` in the query incorrectly.

Initially, I thought you were asking about `"` vs. `%22`. I can't find anything in RFC 3986 that says you *should* escape `"`, but it often is. I've updated the tests to allow either.

**Comment by ChristianGruen** [comment]
> The `tel:` scheme is non-hierarchical and has an explicit leading plus, see [RFC 3966](https://www.ietf.org/rfc/rfc3966.txt). We don't mandate what non-hierarchical schemes are implemented so I think you could exclude that test if you wanted to. Or we could remove it, if you'd prefer.

If it’s implementation-defined what schemes are supported, we’ll probably need to remove those tests.

> For `fn-parse-uri-036`, I think you're handling the `&` in the query incorrectly.

Maybe that’s due to the XPath/XQuery compatibility issue with quotes. It seems the parsing problem case can be fixed by replacing the double quotes…

> "query": "s=%22hello world%22&sort=relevance",
> "uri": "https://example.com:8080/path?s=%22hello world%22&sort=relevance"

…with backticks:

>  "query": `s=%22hello world%22&sort=relevance`,
>  "uri": `https://example.com:8080/path?s=%22hello world%22&sort=relevance`

**Comment by ndw** [comment]
Of course, GitHub mangled the back ticks in your example. :-)

But I'm confused about where the problem is wrt the test results. The results in the test suite are in a CDATA section, so the `&` before `sort` shouldn't require any additional escaping. Or am I just confused?

**Comment by ChristianGruen** [comment]
> Of course, GitHub mangled the back ticks in your example. :-)

True… Fixed that.

> But I'm confused about where the problem is wrt the test results. The results in the test suite are in a CDATA section, so the `&` before `sort` shouldn't require any additional escaping. Or am I just confused?

The escaping is required as the ampersand occurs within quotes (without CDATA, you’d need to write `&amp;amp;`). If the Saxon test suite driver accepts the test, it could be that the assertions are parsed as XPath, not XQuery (Michael mentioned this in the past; I couldn’t reproduce it by myself, as we parse everything as XQuery).

**Comment by ChristianGruen** [comment]
Examples for escaping `&amp;`:
* https://github.com/qt4cg/qt4tests/blob/master/prod/Literal.xml#L508-L526
* https://github.com/qt4cg/qt4tests/blob/master/fn/expanded-QName.xml#L50-L59
*

**Comment by michaelhkay** [comment]
In catalog-schema.xsd it is documented that "The assert element contains an XPath expression whose effective boolean value must be true". However, we should try to accommodate people who want to evaluate the assertion using XQuery, by ensuring that it does not use ampersands in string literals. This is easier to achieve in 4.0 by using backticks.

**Comment by ndw** [comment]
I don't understand this comment from 26 June:

>fn:encode-for-uri is applied on the members of the path-segments array, but in various tests, the path segments are adopted unchanged in the results. Maybe a rule is missing to restrict the encoding to specific cases/schemes/whatever?

I think it applies to `build-uri`, but for example, the test that includes "a b" has an expected result that includes `a+b` which is encoded. What am I missing?

**Comment by ChristianGruen** [comment]
> I think it applies to `build-uri`, but for example, the test that includes "a b" has an expected result that includes `a+b` which is encoded. What am I missing?

Take `fn-build-uri-from-parse-021` as example: In the test suite, it seems to be `mailto://John.Doe@example.com` instead of `mailto://John.Doe%40example.com`. Next, for `a b`, I would have expected `a%20`, as `encode-for-uri(' ')` returns `%20`.

More questions are  welcome.

**Comment by ndw** [comment]
Right. I can see why I get the results I do, but I can't justify them. I'm only encoding the path parts of hierarchical URIs. Even in hierarchical URIs, I only encode spaces and `/` characters and I'm not sure I can justify that either.

With respect to encoding spaces, I think we should accept either `+` or `%20` as they're equivalent and `+` is easier to read. (It turns out, I special case spaces to plus.)

**Comment by ChristianGruen** [comment]
> With respect to encoding spaces, I think we should accept either + or %20 as they're equivalent and + is easier to read. (It turns out, I special case spaces to plus.)

I’m wondering how we could do this. Are you thinking about allowing both results for `fn:encode-for-uri`? In all the tests, we’d then need to provide both alternatives.

**Comment by ndw** [comment]
Here's my interpretation:

`fn:parse-uri("//uncname/path/to/file", map { "unc-path": true() })`

* `string = "//uncname/path/to/file"`
* There’s no fragment or query
* “Finally, if the string does not match the expression”, `scheme=()`, `filepath=()` and `string` is unchanged.
* “If the scheme is the empty sequence, the unc-path option is true,  and the string matches ^//[^/].*$, …”, `scheme="file"`, `filepath=string`.
* The file: scheme is known to be hierarchical, `hierarchical=true()`
* “Otherwise, if the string matches ^///*([^/]+)(/.*)?$”, `authority="uncname"`, `string="/path/to/file"`
* “If the authority matches ^(([^@]*)@)?([^:]+)(:([^:]*))?$,…” `host="uncname"`
* “, otherwise path is the whole string”, `path="/path/to/file"`.
* ”A path-segments sequence is constructed by tokenizing the string on the path separator and applying uri decoding on each token.” `path-segments = ("", "path", "to", "file")`

`fn:parse-uri("file:///c:/path/to/file")`

* `string = "file:///c:/path/to/file")`
* There’s no fragment or query
* “Otherwise, if the string matches ^([a-zA-Z][A-Za-z0-9\+\-\.]*):(.*)$”, `scheme="file"`, `string="///c:/path/to/file"`, `filepath=()`
* The file: scheme is known to be hierarchical, `hierarchical=true()`
* “If the string matches ^//*([a-zA-Z]:.*)$, …”, `authority=()`, `string="c:/path/to/file"`

Yeah, that’s a bug. It should say `string="/c:/path/to/file"`, you need to preserve the leading slash.

`fn:parse-uri("ldap://[2001:db8::7]/c=GB?objectClass?one")`

* `string = "ldap://[2001:db8::7]/c=GB?objectClass?one")`
* “If the string matches ^(.*)\?([^\?]*)$, …”

Yeah, that's also a bug. In a recent revision, I discovered that `?` is allowed in the query part, so that regex is wrong.

Nice catch(es)!

**Comment by ChristianGruen** [comment]
> * “Otherwise, if the string matches ^///*([^/]+)(/.*)?$”, `authority="uncname"`, `string="/path/to/file"`

With the given rule set, only the highlighted rule will apply:

![image](https://github.com/qt4cg/qtspecs/assets/196589/1ee111ec-0116-4517-b2a1-66b35adaa0be)

**Comment by ChristianGruen** [comment]
Maybe it would speed up things to have a joint look at your implementation, and align it with the spec?

**Comment by ChristianGruen** [comment]
> Sure. You're more than welcome to look. It's [ParseUri.java](https://gist.github.com/ndw/e80410fb2c3ba8736f4d4a0a19a8824f). That's the core function, I haven't tried to provide all of the various context and such.

Thanks. One thing I noticed is that the rule with the `unc-path` option may need to be moved before the `hierarchical` rules in the spec (this difference should explain why our results differ for `fn:parse-uri("//uncname/path/to/file", map { "unc-path": true() })`).

**Comment by ChristianGruen** [comment]
@ndw What do you think might be the best way to push this forward? Do you think it’s a) your `ParseUri.java` implementation, b) the test cases or c) the specification that we should take as reference?

**Comment by ChristianGruen** [comment]
> I don't think any one implementation should be taken as normative. If looking at my implementation helps you see what it's doing differently than yours, that's cool. But if theyr'e doing different things, we need the specification prose to clearly identify which behavior is correct and which is an error.

Thanks, Norm. In that case, I hope my comment further above (https://github.com/qt4cg/qtspecs/issues/566#issuecomment-1789534261) helps to align the specification with the behavior of the implementation (provided that the latter one does what is expected).

**Comment by ChristianGruen** [comment]
@ndw Do you think I can help you in some way to push this further?

**Comment by ChristianGruen** [comment]
@ndw @michaelhkay That was the issue I referred to in today’s meeting. Questions are welcome.

**Comment by ndw** [comment]
Thank you. I will try to reply before our next meeting.

**Comment by ndw** [comment]
There are a lot of comments on this issue and I'm not 100% sure I know which ones are still applicable. I thought it might be easiest if I reviewed the test results that @ChristianGruen provided:

`fn-parse-uri-008`: (and `fn-parse-uri-030`, `fn-parse-uri-036`, `fn-parse-uri-043b`, `fn-parse-uri-043c`)
```
let $amp := codepoints-to-string(38) return fn:parse-uri("https://example.com:8080/path?s=%22hello world%22" || $amp || "sort=relevance")
Result: map { …"query-parameters": map { "s": "%22hello world%22", "sort": "relevance" } }
Expect: map { …"query-parameters": map { "s": """hello world""", "sort": "relevance" } }
```

I think the expeced results are correct because `fn:parse-uri()` performs `fn:decode-from-uri()` on the query parameter values.

---

`fn-parse-uri-011c`:
```
fn:parse-uri("//uncname/path/to/file", map { "unc-path": true() })
```

I think your results are correct. I’m not handling unc-path as described in the spec. I'm not 100% sure I like the rules in the spec, but I should still implement them!

---

`fn-parse-uri-012`: (and `fn-parse-uri-013`, `fn-parse-uri-014`, `fn-parse-uri-015`)
```
fn:parse-uri("file:///c:/path/to/file")
Result: map { "filepath": "/c:/path/to/file", …
Expect: map { "filepath": "c:/path/to/file", …
```

I think the expeced results are correct because:

> If the scheme is not known or is known to be `file` and the string matches `^/*(/[a-zA-Z]:.*)$`, the authority is empty and the string is the first match group.

The first match group in this case will remove all the leading slashes.

---

`fn-parse-uri-024:`
```
fn:parse-uri("telnet://192.0.2.16:80/")
Result: map { … 
Expect: map { …"path-segments": fn:replicate("", 2)
```

I think the expected results are correct because the path is “/” and

> A path-segments sequence is constructed by tokenizing the string on the path separator and applying uri decoding on each token.

---

`fn-parse-uri-035`:
```
fn:parse-uri("querty:///abc")
Result: map { "authority": "abc", "scheme": "querty", "host": "abc", "hierarchical": true(), "uri": "querty:///abc" }
Expect: deep-equal($result?path-segments, ('', 'abc')), [basex:error] Value has no boolean representation: ()
```

I think the expected results are correct because after removing the scheme, the remaining string is `///abc` and the following rule applies:

> Otherwise, if the string matches ^///*([^/]+)?(/.*)?$, the authority is the first match group and the string is the second match group.

That reduces the `string` to `/abc`. That becomes the path and the path segments are `('', 'abc')`.

---

`fn-parse-uri-038`:
```
fn:parse-uri("file://c|/path/to/file")
Result: map { "filepath": "/path/to/file", …
Expect: map { "filepath": "c:/path/to/file" …
```

I think there’s a bug in the spec. When we first look at the string, we consider whether it might be a Windows path by looking for `^[a-zA-Z][:|]`. Later, when we’re considering only the path, we only look for `^/*(/[a-zA-Z]:`. I think we should allow `|` in the latter case as well.

---

`fn-parse-uri-042`:
```
fn:parse-uri(`http://example.com/path?a=1&b=2%264&a=3`)
```

I think this test had character encoding problems. (Fixed by a PR on the test suite earlier today.)

---

`fn-parse-uri-043`:
```
fn:parse-uri("https://qt4cg.org/specifications/xpath-functions-40/Overview.html#")
Result: map { …
Expect: map { …, "fragment": "" }
```

I think the expeced results are correct because

> If the string matches `^(.*?)#(.*)$`, the string is the first match group and the fragment is the second match group.

Perhaps we should have a rule that says the fragment identifier is discarded if it’s the empty string.

---

`fn-parse-uri-043a`:
```
fn:parse-uri(`http://example.com/%20!%22%23$%25&'()*%2B,-.%2F0123456789:;%3C=%3E%3F?a=%20!%22%23$%25%26'()*%2B,-&b=./0123456789:;%3C%3D%3E?#%20!%22%23$%25&'()*%2B,-./0123456789:;%3C=%3E?`)
```

I think this test had character encoding problems. (Fixed by a PR on the test suite earlier today.)

---

`fn-parse-uri-043d`:
```
fn:parse-uri(`http://example.com/🤷 ¡¢£¤ǌ†𓇌𓆑🏴󠁧󠁢󠁷󠁬󠁳󠁿?a=🤷 ¡¢£¤ǌ&b=†𓇌𓆑🏴󠁧󠁢󠁷󠁬󠁳󠁿#🤷 ¡¢£¤ǌ†𓇌𓆑🏴󠁧󠁢󠁷󠁬󠁳󠁿`)
````

The results look the same to me. ¯\\_(ツ)_/¯

**Comment by ChristianGruen** [comment]
Thanks, @ndw!

> fn-parse-uri-008: (and fn-parse-uri-030, fn-parse-uri-036, fn-parse-uri-043b, fn-parse-uri-043c)
> I think the expeced results are correct because fn:parse-uri() performs fn:decode-from-uri() on the query parameter values.

You are so right, I missed that.

For `fn-parse-uri-043b` and `fn-parse-uri-043c` and (missing here `fn-parse-uri-043a`), I believe a comment should be added in the spec that fragments need to be decoded as well (or the tests should be revised).

> fn-parse-uri-012: (and fn-parse-uri-013, fn-parse-uri-014, fn-parse-uri-015)

> If the scheme is not known or is known to be file and the string matches `^/*(/[a-zA-Z]:.*)$`, the authority is empty and the string is the first match group.
> The first match group in this case will remove all the leading slashes.

Please note that the group `(/[a-zA-Z]:.*)` starts with a slash… Maybe it needs to be removed?

> fn-parse-uri-024:

Thanks; I now understand how this is to be interpreted (I made the mistake to drop empty segments).

I must say it’s somewhat confusing, as `telnet://192.0.2.16:80` yields 0 segments, whereas `telnet://192.0.2.16:80/` yields 2 of them… What’s the rationale behind this? An exaplanatory note in the spec could be helpful.

> fn-parse-uri-035

> Otherwise, if the string matches ^///*([^/]+)?(/.*)?$, the authority is the first match group and the string is the second match group.
> That reduces the `string` to `/abc`. That becomes the path and the path segments are `('', 'abc')`.

The query `replace('//abc', '^///*([^/]+)?(/.*)?$', '$1|$2')` returns `abc|`, so I believe that `/abc` is assigned as `authority` here, whereas `string` is going to be empty. Do you agree?

> fn-parse-uri-043

> Perhaps we should have a rule that says the fragment identifier is discarded if it’s the empty string.

Yes, that would be great (and consistent).

> The results look the same to me. ¯\(ツ)/¯

True indeed. We’ll check our test suite and make it emoji-stable.

Looking forward to the `build-uri` test cases…

**Comment by ndw** [comment]
The immediate and obvious problem with the build URI tests is that the specification says the path segments are encoded with `fn:encode-for-uri()` and that's just much too aggressive. 

I think an earlier version of the specification described encoding differently and we changed it to use `fn:encode-for-uri()` because that seemed simpler and re-used an existing function. I apparently didn't update our implementation. :-( But I don't thnk that works anyway.

Given: `http://example.com/path%2Fto/a=b`, we want to parse that into path segments like so: `('', 'path/to', 'a=b')`. One of the purposes of path segments is to give the user access to decoded characters directly. Unfortunately, this is a lossy translation. Given: `http://example.com/path%2Fto/a%3Db`, we get exactly the same path segments.

There's no absolutely correct answer here. Not decoding the URI parts means users have to do a lot more work. Generally speaking, I think that users only regularly encode characters that *have* to be encoded, like `/` and `&`. My earlier proposal for encoding the path segments was to leave **unencoded** the following characters `A-Za-z0-9-._~!$&\;()*+,;=:@`

Those are, I believe, the general- and sub-delimiters from RFC 3986 *except* `#`, `'`, `/`, `?`, `[` and `]`.

I'm not sure I have a principled rationale for all of those characters. The `#`, `?`, and `/` characters are escaped because leaving them unescaped changes the way the URI is parsed. I think `&` should be in that list on those grounds and I don't recall leaving it out on purpose. Seems like `"` should probably be in that list if `'` is. And I can't explain the square brackets.

😦

**Comment by ChristianGruen** [comment]
…sounds like an unrewarding task. I believe this this was the first commit for `fn:build-uri`, maybe it helps: https://github.com/qt4cg/qtspecs/commit/c7d0d5fa2370d0d4e844cd0ceb85cb68600b9b38

**Comment by ndw** [comment]
> For fn-parse-uri-043b and fn-parse-uri-043c and (missing here fn-parse-uri-043a), I believe a comment should be added in the spec that fragments need to be decoded as well (or the tests should be revised).

I’ll add the comment.

> `fn-parse-uri-012`: (and `fn-parse-uri-013`, `fn-parse-uri-014`, `fn-parse-uri-015`)
>
> Please note that the group (/[a-zA-Z]:.*) starts with a slash… Maybe it needs to be removed?

I don’t think so. The string will begin with a slash when we get here, perhaps more than one. The goal of that match is to turn `/////c:/abc` into `/c:/abc`. 

> `fn-parse-uri-035`
>
> Otherwise, if the string matches ^///*([^/]+)?(/.)?$, the authority is the first match group and the string is the second match group. That reduces the string to /abc. That becomes the path and the path segments are ('', 'abc').
>
>The query replace('//abc', '^///*([^/]+)?(/.*)?$', '$1|$2') returns abc|, so I believe that /abc is assigned as authority here, whereas string is going to be empty. Do you agree?

The original URI matches a scheme followed by a colon followed by more characters. In this case, the scheme and colon are removed and what remains is the rest of the string. I think you should begin with “///abc”, not “//abc”.

But I guess there’s an ambiguity here. Matching `///abc` against `^///*([^/]+)?(/.)?$` is either:
`///(abc)()` or `//()(/abc)`. I intended the former in the specification. It’s going to be a little messier, but I think I can clarify that.

**Comment by ChristianGruen** [comment]
Some more feedback (which might already be outdated, given your new pull request, #1098):

> > `fn-parse-uri-012`: (and `fn-parse-uri-013`, `fn-parse-uri-014`, `fn-parse-uri-015`)
> > Please note that the group (/[a-zA-Z]:.*) starts with a slash… Maybe it needs to be removed?
> 
> I don’t think so. The string will begin with a slash when we get here, perhaps more than one. The goal of that match is to turn `/////c:/abc` into `/c:/abc`.

…the problem I think is that the (currently) expected result of `fn-parse-uri-012` is `c:/path/to/file`, not `/c:/path/to/file`:

> fn:parse-uri("file:///c:/path/to/file")
> Result: map { "filepath": "/c:/path/to/file", …
> Expect: map { "filepath": "c:/path/to/file", …

> > `fn-parse-uri-035`
> The original URI matches a scheme followed by a colon followed by more characters. In this case, the scheme and colon are removed and what remains is the rest of the string. I think you should begin with “///abc”, not “//abc”.

Did you mean “//abc”, not “///abc” ?

> But I guess there’s an ambiguity here. Matching `///abc` against `^///*([^/]+)?(/.)?$` is either: `///(abc)()` or `//()(/abc)`.

Yes, I think needs to be rewritten (I guess the regex itself is unambiguous, but it seems to do the wrong thing).

**Comment by ChristianGruen** [comment]
Our current test output:
* Latest: [fn-parse-uri-2024-03-19.log](https://github.com/qt4cg/qtspecs/files/14653104/fn-parse-uri-2024-03-19.log)
* Before: [fn-parse-uri-2024-03-18.log](https://github.com/qt4cg/qtspecs/files/14653103/fn-parse-uri-2024-03-18.log)

**Comment by ChristianGruen** [comment]
I’ll close the issue and open a new one once I have something to report.
