### ISSUE TITLE
[FO] fn:namespace-uri-for-prefix no longer supports passing a prefix by string

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#60]
The type signature of the `$prefix` variable has changed from `xs:string?` to `union(xs:NCName, enum(''))?`. This means that passing a prefix like `"fn"` will no longer work as it is not an `xs:NCName` and is not a zero-length string (`enum('')`).

__Note:__ The only other affected function is the new `fn:in-scope-namespaces` method. It would be useful in some cases to be able to pass the value as an `xs:string` (e.g. `"fn"`) without having to cast the value.

**Comment by michaelhkay** [comment]
The revised signature takes advantage of the new feature proposed in the coercion rules, that allow for implicit down casting from xs:string to xs:NCName provided the value is castable.

However, there is a potential compatibility problem in that passing an incorrect value becomes a type error rather than a dynamic error, and might result in a different error code.

**Comment by ndw** [comment]
The CG agreed to close this issue at [meeting 024](https://qt4cg.org/meeting/minutes/2023/02-28.html#closure)
