### ISSUE TITLE
Support using different input/output element namespaces

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#65]
## Use Case

There have been requests for specifying the output namespace in XQuery akin to the `@xpath-default-namespace` element in XSLT. With the element and type namespaces now being able to be set independently, it would be a good idea to make this change as well, splitting the input and output default XML namespaces.

## Grammar

    DefaultNamespaceDecl ::= "declare"  "default"  ((("input" | "output")? "element")  |  "type"  |  "function")
                             "namespace"  URILiteral

## New Semantics

The *default element namespace* static context item is split into a *default input element namespace* that applies to input element contexts (e.g. path steps), and a *default output element namespace* that applies to output element contexts (e.g. direct/constructed elements).

The *scope* of the default namespace declaration is the `element`, `function`, `input element`, `output element`, or `type` namespace specified in the declaration.

A default namespace declaration with the *element* scope will set any of the *input element*, *output element*, and *type* namespaces that have not been set by a corresponding *input element*, *output element*, or *type* scoped default namespace declaration.

> Example:
>
> Given `declare default input element namespace "A"; declare default element namespace "B";`, the *output element* and *type* namespaces will be specified by the *element* scope default namespace declaration "B", and the *input element* namespace will be specified by the *input element* scope default namespace declaration "A".

## TODO

Map all element symbols/contexts as using either the *input element* or *output element* default namespace for NCName EQNames.

**Comment by michaelhkay** [comment]
Let's remind ourselves of the problem we are trying to solve.

The basic problem is that specifying `xmlns="xxxx"` or `xmlns:foo="bar"` on a direct element constructor affects both the in-scope namespaces of the constructed element node, and also the namespace bindings (including the default namespace) for element names in path expressions within its scope. This isn't a big problem for explicit prefixes, since it's always possible to choose disjoint sets of prefixes, but it's a problem for the default namespace, especially in the case where the input document has elements that are in no namespace, while the output document is to be constructed with a default namespace (xmlns="foo").

With that in mind, I'm wondering if a more economical solution would be: rather than having separate "input element" and "output" element default namespaces, have a boolean switch that says that (a) the default element namespace declared in the prolog does not affect direct element constructors, and (b) xmlns declarations on direct element constructors do not affect the interpretation of unprefixed names in path expressions within their scope.  Syntax perhaps `declare default element namespace fixed := "uri"`.

Note also the proposed WithExpr, which needs review and revision.

**Comment by gimsieke** [comment]
The issue that a default namespace declaration on a direct element constructor sets the default element/type namespace for expressions inside the constructor arose yesterday on the [BaseX mailing list](https://mailman.uni-konstanz.de/pipermail/basex-talk/2023-March/017885.html). 

I thought that the current prose in the [spec](https://www.w3.org/TR/xquery-31/#id-element-constructor) is too fuzzy to indisputably demand exactly this behavior. It says:

> Note that both the statically known namespaces and the default element/type namespace may be affected by [namespace declaration attributes](https://www.w3.org/TR/xquery-31/#dt-namespace-decl-attr) found inside the element constructor.

Not suggesting anything substantive here, but if the rules stayed as they are, at least the fact that the namespace declared in the default `xmlns="…"` declaration becomes the default namespace for selecting elements in expressions inside the constructor should be stated more clearly, for example:

> The namespace URI of a default namespace declaration attribute in a direct element constructor will become the default element/type namespace for expressions inside the constructor. 

And there should probably be a note that the so-called computed element constructor, for example `element Q{http://www.w3.org/1999/xhtml}html { … }`, does not set the default element/type namespace for the expressions that populate the element’s content.

(If I may disclose: Christian confessed to me in private that BaseX’s behavior is like it is not because of his own spec exegesis but because someone else interpreted the spec in that way and wrote a test accordingly…)

But if you alter the rules for 4.0 anyway, I’m confident that you will support them with less fuzzy prose.

**Comment by michaelhkay** [comment]
In response to @gimsieke I think the current spec is unambiguous. It says in 4.7.4.1 Axes:

> An unprefixed QName, when used as a name test on an axis whose [principal node kind] is [** word missing here **] is interpreted as follows:
> 
> If the [default namespace for elements and types] is a namespace URI, then the name is interpreted as having that namespace URI.
> If the [default namespace for elements and types] is absent, then the name is interpreted as being in no namespace.
> 

While 4.13.1.2 says (of namespace declarations in direct element constructors):

> If the name of the namespace declaration attribute is xmlns with no prefix, then the namespace URI specifies the [default namespace for elements and types] of the constructor expression

I propose that we resolve the issue by allowing the prolog to say:

`declare fixed default element namespace "http://some.namespace";`

and the presence of the "fixed" keyword means that `xmlns=""` on a direct element constructor within that module no longer changes the default namespace for elements and types.

**Comment by ChristianGruen** [comment]
Resolved: #753.
