### ISSUE TITLE
XQFO presentation of diagnostic functions

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#686]
From an informal discussion on Slack, I feel that clarity is needed in the [Diagnostic tracing](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#diagnostics) section. The problem is that `fn:trace()` and `fn:log()` introduce the terms "trace output" with no definition or explanation, and this is easily confused with the primary output defined by the function signatures, and affects how readers think about the determinism of the functions. "The serialization of the trace output..." implies that the processor will necessarily serialize something, but I doubt that can or should be presumed. More needs to be said about the responsibilities of the processor in the contract for these functions. 

In my opinion, this section would benefit from a brief preamble, providing context to set the stage for the rules. Some draft text for us to discuss:

> Diagnostic tracing functions provide a transfer of information, either from the processor to the dynamic context, or vice versa. 
> 
> The function that transfers information from the processor to the dynamic context, `fn:stack-trace()`, returns a string that can be further processed and used in the XPath expression and elsewhere in a host language. 
> 
> The functions that transfer information from the dynamic context to the processor, `fn:trace()` and `fn:log()`, each have two effects. The first effect, the output, pertains to the returned values, defined by the function signature and essential to the XPath expression. Such output is always deterministic. The second effect, processor behavior, concerns the way the processor handles the values bound to the parameters, supplied for diagnostic tracing. Processor behavior is always directed toward the user or environment that invoked the processor. Actions may include sending messages, serializing the values and writing them to a log file or database, or something else. Unlike the output (the first effect), the results of processor behavior are implementation-defined and nondeterministic with respect to order of the parameter values.

The draft above attempts to avoid "output" to describe the processor-side diagnostics, so as to avoid potential confusion when dealing with the return-type defined in the signature. Where "trace output" appears in each of the rules, "processor behavior" can be used instead.

Questions:
* Any objections, corrections, or suggestions? 
* Any other examples of how a processor might use trace diagnostics?
* Should a paragraph be added to explain briefly how `trace()` and `log()` differ from `xsl:message`? (E.g., a serialized tree should not be presumed.)
* In the informal Balisage birds-of-a-feather discussion this summer, reservations were expressed by participants about the name `log()`. Is it possible to drop the function and simply extend the arity of `trace()` with a parameter `$return-input as xs:boolean? := true()`?

**Comment by ChristianGruen** [comment]
I have to be cautious with feedback as I’ll never be a first-class citizen of the English language. I must admit, though, that the proposed wording is confusing to me (maybe because it differs from the wording I’m used from the spec):

* The [dynamic context](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-dynamic-context) is “defined as information that is needed for the dynamic evaluation of an expression”. I think it’s not correct to state that diagnostic information is transferred from/to the dynamic context: The components of the dynamic context are well-defined, and there has never been a component for processing or storing trace data. Instead, I’d rather say it’s completely ·implementation-defined· how such information is passed on.
* It feels unorthodox to me to say that output is “the effect of a function”. Instead, I would say that a function is evaluated and it creates a result. The result will not necessarily be “output”, but it will rather be further processed by the parent expression, or (at root level) returned to the invoking instance. Output implies to me that something specific happens with a result. It could e.g. be “output as a string”, or “output to standard error”, or a logger.
* I have problems to understanding how a “behavior ”can be “directed”. I would rather say that a processor is designed to behave this or the other way. Once again, it’s the result of an evaluation that is directed somewhere.

Personally, when I read them for the first time, I found the function definitions easy to understand. The only thing that confused me was the “trace data set” (see [XQFO31: fn:trace](https://www.w3.org/TR/xpath-functions-31/#func-trace)), which is why I proposed some changes to the original text.

The name of the function is already discussed in #651. I would like to keep it (no surprise, because I’ve proposed it…): The equivalent function in our processor (`prof:dump`) is used a lot, and it would be tedious to always add an argument to the function call to suppress the result.

**Comment by michaelhkay** [comment]
My reactions to Joels' proposal were much the same as Christian's.

Mike

**Comment by Arithmeticus** [comment]
Thank you both. I'll work on a less misleadingly cataphatic (and intrusive) approach that at least addresses the points of confusion I encountered when I first read this section.

I think it would help to have a couple of simple examples for `fn:trace()` and `fn:log()`, to illustrate the utility. I could come up with my own, but I think @ChristianGruen has probably some real-life examples that could be adapted.

**Comment by ChristianGruen** [comment]
> I think it would help to have a couple of simple examples for `fn:trace()` and `fn:log()`, to illustrate the utility. I could come up with my own, but I think @ChristianGruen has probably some real-life examples that could be adapted.

@Arithmeticus I’d like to contribute, but I don’t know how good examples would need to look like that apply to all processors. In BaseX, `fn:trace` (and equivalent functions for performance measurements, see https://docs.basex.org/wiki/Profiling_Module) are used…

* to debug data (values of variables, intermediate computations) on the command-line or in various user interfaces;
* for forwarding information in productive code (e.g. in web applications) to the database logs.

In other programming languages, similar constructs exist to do the same (`print` commands, `console.log()`, `System.out.println()`, logger interfaces).

Regarding the trace output, as it’s implementation-defined, it may also affect how the output is further processed. See for example the output of… 

```xquery
sum((
  trace((), 'RESULT1: '),
  trace(1, 'RESULT2: '),
  trace((2 to 4), 'RESULT3: ')
))
```

…in different processors:

```php
# Saxon (Zorba’s output looks similar)
RESULT1: : empty sequence
RESULT2:  [1]: xs:integer: 1
RESULT3:  [1]: xs:integer: 2
RESULT3:  [2]: xs:integer: 3
RESULT3:  [3]: xs:integer: 4

# BaseX
RESULT1: ()
RESULT2: 1
RESULT3: (2 to 4)
```

Saxon seems to provide the data type in the output (I didn’t know/remember that). That’s something we don’t; we’re focusing on a representation that can be interpreted as text.

In which use cases (or with which processors) have you used `fn:trace` by yourself?

For `fn:stack-trace`, I‘ve just created a new issue: #689.

**Comment by Arithmeticus** [comment]
Shifting thread to #763.

**Comment by ChristianGruen** [comment]
Resolved.
