### ISSUE TITLE
xsl:function-library: keep, drop, or refine?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#742]
The draft XSLT 4.0 specification (§5.3.2) proposes a new declaration xsl:function-library as a solution to the problem of having to qualify all function names except those in the core namespace. We have not reviewed this proposal.

**Comment by dnovatchev** [comment]
I read this last week and it is a bold attempt to simplify function naming.

My gut feeling was and currently is that the proposed set of rules for disambiguating function names so that the namespace prefixes can be completely dropped - that this actually brings more complexity than it is trying to eliminate.

I personally would feel confused in case the disambiguation works in an unexpected way, and trying to fix such cases would take time and effort.

I believe that any XPath user (this of course includes all XSLT users) has had experience calling functions in their code and thus knows the prefixes for the function names. 

What we would very much like to eliminate is:

- The need to declare any of the standard function namespaces with the standard prefixes: `fn`, `math`, `map`, `array`, `xs`, `ser`, and `err` . Sometimes such namespace declarations occupy more than 50% of the code of a stylesheet module, and these need to be entered in every stylesheet module.
- The need in pure XPath to refer to a function as `Q{uri}name` instead just as `standard-prefix:name`

I think that both of the above problems are solved with the proposed **_[PR for fixed prefixes](https://github.com/qt4cg/qtspecs/pull/470)_**.

We probably need to provide the set of (standard) fixed-prefixes not only in XSLT, but generally for XPath and any host of XPath.

**Comment by michaelhkay** [comment]
Thanks for review. I'm inclined to agree. Sometimes (particularly with namespaces!) trying to make things easier actually makes things more complicated.

**Comment by Arithmeticus** [comment]
When I first saw the name `xsl:function-library` I thought it would be a container for one or more `xsl:function`s, i.e., it really is a library. But it currently is just a way of grouping `xsl:function-namespace`, which suggests to me that a more accurate name would be `xsl:function-namespaces`. At any rate, 'library' is a misleading component in the name. Unless its job is somehow expanded to do more function configuration. In which case `xsl:function-settings` would be a good alternative.

**Comment by michaelhkay** [comment]
We decided to drop the feature.
