### ISSUE TITLE
fn:transitive-closure: signature; remarks; too specific?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#754]
I have problems grasping why `fn:transitive-closure` returns a function. Wouldn’t it be more consistent with the remaining function set, and easier, to pass on the input as the first argument and directly create the result?

```xquery
fn:transitive-closure(
  $node  as node(),
  $step  as function(node()) as node()*,	
  $min   as xs:nonNegativeInteger?       := 1,
  $max   as xs:positiveInteger?          := ()
) as node()*
```

It would also be easier then to use the function within chains:

```xquery
$nodes =!> transitive-closure(fn { * }) => count()
```

**Comment by ChristianGruen** [comment]
I just noticed we already have #554 for further notes on this function. As the scope of that issue is slightly different, I’ll keep mine open. Some more comments:

* I wonder why `$min` has been added: Is there a particular need to loop 10 times if fewer iterations are required to compute the result? Wouldn’t it be better to use a boolean option instead to include the original node? Or does it rather mean that the first $min computed results are to be ignored before the closure is computed?
* The summary of the function is a bit cryptic; it doesn’t really tell what the function does: “Given a function F that navigates from one node to other nodes, returns a function that applies F repeatedly.”.

Overall, the feature feels a bit specific to me. I think an extension library would be a better place for it. I can imagine it can be helpful, but I never came across a use case for it by myself.

**Comment by michaelhkay** [comment]
The function was changed to return a function at Michael Sperberg-McQueen's suggestion, largely I think because it's closer to the mathematical definition.

The $max parameter was added primarily so you could protect against non-termination if the base function creates new nodes. The $min parameters was added partly for symmetry and partly because there are use cases for the values 0 and 1. Personally I'd be happy to drop both - force $min to 1 (because you can always add the starting node back in to the result), and say that termination isn't guaranteed if the base function is badly behaved.

I do feel strongly that there are use cases for the function -- I've had to implement it quite a few times, and it's not trivial to get it right, especially if you have to deal with cycles.

**Comment by ChristianGruen** [comment]
I see.

I certainly believe that there are use cases; I'm just not sure if the scope is general enough to embed this in the core function set. Wouldn't there be many other graph algorithms that could be equally relevant?

Next, I'm struggling to get a working implementation with the given rule set. It would be very helpful if an equivalent XQuery function could be added, or a link to any other pseudo code.

**Comment by michaelhkay** [comment]
I believe that the following logic implements the function for the min=1 max=infinity case:

```
          declare function local:tc-inclusive(
                $start  as node()*,
                $step as (function(node()) as node()*)	
                ) as node()* {
                   let $nextStep := $start ! $step(.)
                   return (if (exists($nextStep except $start))
                           then local:tc-inclusive($start | $nextStep, $step)
                           else $start)
            };
            declare function local:tc-exclusive(
                $start  as node()*,
                $step as (function(node()) as node()*)	
            ) as node()* {
                local:tc-inclusive($start ! $step(.), $step)
            };
            declare function local:transitive-closure(
                $step as function(node()) as node()*
                ) as function(node()*) as node()* {
                  local:tc-exclusive(?, $step)
            };
```

Essentially, tc-inclusive computes the transitive closure with min=0; tc-exclusive does the same with min=1, and local:transitive-closure adapts this to return a function rather than a concrete evaluation.

It look me about an hour to develop this and test it, which I think is a good indication of why the function is needed.

>Wouldn't there be many other graph algorithms that could be equally relevant?

Possibly, but in my experience this is the one I need most often. Next on my list would be testing for acyclicity.

**Comment by ChristianGruen** [comment]
Thanks for spending the full hour on this.

I must admit I still don't understand how the solution would need to like for `$min` > 1. I assume it's hard to get this realized in XQuery?

**Comment by michaelhkay** [comment]
I don't think it's too difficult. You could pass the current depth as a parameter, and if the depth is < $min, you cut out the `$start | ` part, and if it's > $max, you end the recursion. But I'll propose a version that cuts out the complexity of the $min and $max parameters - I think we over-engineered it.
