### ISSUE TITLE
Annotations: Make default namespace explicit

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#821]
In XQuery, the default namespace for annotations is `http://www.w3.org/2012/`. It’s the only namespace for which no prefix exists, and I think we should change that. `ann` feels like a reasonable choice to me as we tend to have short prefixes (such as `err` for errors).

**Comment by rhdunn** [comment]
Doesn't this cause an issue due to the annotation definitions being in an implicit "default annotation namespace"? I.e. `%private`, etc. would need to be `%ann:private` if the annotation namespace were made explicit, which would break XQuery.

`err` is given a name in the spec because it is referenced in many places in the spec. It's given a binding in XQuery 4.0 (3.1 didn't have this in the static context) to make it easier for users to write catch blocks.

The annotation namespace is used in various places in the spec, so this could be useful for that, but I think it would make the spec more confusing. Maybe something like:

>A variable declaration may use annotations to specify that the variable is `%private` or `%public` (which is the default).

to:

**Comment by ChristianGruen** [comment]
@rhdunn Thanks for your assessment.

I wanted to keep the `%private` and `%public` annotations rules unchanged (but I like your suggestion to revise the text).

The reasons for my suggestion are:
* The annotation namespace URI is the only one for which no prefix exists.
* The prefix-less syntax implies that the standard annotations have no namespace. With the prefix, you can make the prefix visible by writing `%ann:public` instead of `%public`. That’s similar to `fn:true()`, which some people prefer over `true()` (one difference certainly is that the default function namespace can be changed).

For existing users, nothing would change, and the `ann` prefix can always be overwritten.

**Comment by benibela** [comment]
It is not an annotation namespace when it is used for annotations *and options*

And it is called `http://www.w3.org/2012/xquery` not `http://www.w3.org/2012/annotations`

This looks like it was supposed to be used for any feature that is XQuery-only. 

Then the prefix should be `xquery`: if it gets any

**Comment by ChristianGruen** [comment]
> It is not an annotation namespace when it is used for annotations _and options_

Good point, I missed this (although Reece quoted the relevant part of the spec). `xquery` would be fine as well.

**Comment by rhdunn** [comment]
I'm happy with adding an `xquery` (or alternatively `xq`) namespace for this to the static context.

**Comment by ChristianGruen** [comment]
> I'm happy with adding an `xquery` (or alternatively `xq`) namespace for this to the static context.

:+1: for `xq`
