### ISSUE TITLE
New sequence functions: names

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#844]
Observations:

A. What about renaming `fn:contains-sequence`, `fn:starts-with-sequence` and `fn:ends-with-sequence` to `fn:contains-items`, `fn:starts-with-items` and `fn:ends-with-items`, in alignment with `fn:items-at`, `fn:items-before`, etc.? If we add equivalent functions for arrays, it could be `array:contains-members`, etc.

B. It seems confusing to have `fn:items-starting-where` and `fn:items-after`, instead of `fn:items-starting-after`. Maybe we can think of alternative (shorter) names for `fn:items-starting-where` and `fn:items-ending-where`? – I know we’ve discussed before; I raised it again due to user feedback.

**Comment by dnovatchev** [comment]
> Observations:
> 
> A. What about renaming `fn:contains-sequence`, `fn:starts-with-sequence` and `fn:ends-with-sequence` to `fn:contains-items`, `fn:starts-with-items` and `fn:ends-with-items`, in alignment with `fn:items-at`, `fn:items-before`, etc.? If we add equivalent functions for arrays, it could be `array:contains-members`, etc.

I think a better name for `fn:contains-items`, is **`fn:has-subsequence`**. The former doesn't at all imply that the contained items must be contiguous.

The same about the proposed: `fn:starts-with-items` and `fn:ends-with-items`. More precise names are: **`fn:starts-with-sequence`** and **`fn:ends-with-sequence`** - `starts-with-items` could mean: _starts with these items in any order or even in any number of occurrences_.

I would even prefer: **`has-prefix`** and **`has-suffix`**

**Comment by ChristianGruen** [comment]
> The former doesn't at all imply that the contained items must be contiguous.

True, good point. Maybe `fn:items-before` could then be renamed to `fn:sequence-before`, etc.

**Comment by michaelhkay** [comment]
Well an analogy with string functions might suggest subsequence-before, subsequence-after, etc. But the names become unwieldy - I tend to prefer shorter names, rather than trying to capture the entire semantics of the function in its name.

Note also that the "contains-sequence" family is still missing "sequence-equal" as proposed in issue #99.

One thing I have found with these functions is that by supplying a suitable callback function for item comparison, they have many applications beyond equality testing. For example, `contains-subsequence($x, 1 to 4, function($x, $y){$x lt 0})` returns true if the first argument contains a sequence of four negative numbers. This might affect how we choose to name the functions.

**Comment by ChristianGruen** [comment]
> I tend to prefer shorter names, rather than trying to capture the entire semantics of the function in its name.

Me too; I’m just a bit confused what are our naming guidelines, or if it makes sense at all to aim for such, in particular, for a aligning the functions for arrays (#843): I assume we’ll then have `array:contains-array` and `array:members-before`?

> `contains-subsequence($x, 1 to 4, function($x, $y){$x lt 0})` returns true if the first argument contains a sequence of four negative numbers. This might affect how we choose to name the functions.

Indeed the “comparator” parameter rather resembles a predicate in this example. `contains-matches($input, $subsequence, $predicate)` or similar, and `array:contains-matches`? Once again, it might not be obvious with this name (as Dimitre suggested) that the matches must be contiguous.

**Comment by michaelhkay** [comment]
Suggestion:

1. `contains-sequence`, `starts-with-sequence`, and `ends-with-sequence` become `contains-subsequence`, `starts-with-subsequence`, and `ends-with-subsequence`
2. `items-before` and `items-after` become `subsequence-before` and `subsequence-after`
3. `items-starting-with` and `items-ending-with` are dropped, as they can be expressed using `subsequence($s, 1, index-where(...)[1])` and `subsequence($s, index-where(...)[1]` respectively.
4. corresponding functions `a:contains-subarray`, `a:starts-with-subarray`, `a:ends-with-subarray`, `a:subarray-before`, and `a:subarray-after` are added.
5. We need a function for matching an entire sequence or array (issue #99) and I propose `matches-sequence` and `a:matches-array`. I prefer to use "matches" rather than "equals" as the comparison function does not need to have equality semantics.

**Comment by ChristianGruen** [comment]
1.–4. looks just fine to me.

**Comment by dnovatchev** [comment]
Not sure about point 5.

The word "matches" brings confusion, uncertainty and questions. What exactly "matches" means? Like in a RegEx ?

The most frequent and simplest comparison is and will be for equality, so let us give exactly this to the users.

Additionally, if someone wants a more evolved functionality, that's OK -- have a specific function with the word "matches" in its name.

**Comment by ChristianGruen** [comment]
I’ve created a pull request for 1-3.
I’ve updated #844, reflecting 4. the proposal for arrays.
For 5., we can use #99.

**Comment by ChristianGruen** [comment]
…continuing the discussion from the pull request, #855:

If we kept `subsequence-starting-where`, the length of the function names would really get awkward; we would get queries like…

```xquery
('A', 'B1', 'B2', 'C')
=> subsequence-starting-where(fn { starts-with(., "B") })
=> subsequence-before(fn { starts-with(., "C") })
```

…or even…

```xquery
['A', 'B1', 'B2', 'C']
=> array:subarray-starting-where(fn { starts-with(., "B") })
=> array:subarray-before(fn { starts-with(., "C") })
```

Next, as I’ve mentioned in the original comment, users would still be confused why `array:subarray-before` is not called `array:subarray-starting-before`.

I'd be very much in favor of resorting to `fn:take-while` and `fn:drop-while`/`fn:skip-while`, which are available in various other languages. The query above could be written much shorter without losing comprehensibility (as I believe):

```xquery
('A', 'B1', 'B2', 'C')
=> drop-while(fn { . < 'B' })
=> take-while(fn { . < 'C' })
```

As an alternative, we could have one function with an optional start and end predicate, inspired by the existing `fn:subsequence` function:

```xquery
('A', 'B1', 'B2', 'C')
=> subsequence-where(fn { . >= 'B' }, fn { . < 'C' })
```

The existing examples for the currently 4 functions could all be rewritten to use `take-while`/`drop-while` or `subsequence-where`.

**Comment by michaelhkay** [comment]
`take-while` and `drop-while` seem terribly imperative in form. I know there are precedents, for example get() and put() and remove(), but I much prefer function names that describe the relationship of the output to the input, rather than using an imperative verb: `tail()` rather than `remove-first()`.

**Comment by ChristianGruen** [comment]
> `take-while` and `drop-while` seem terribly imperative in form. 

Aren't filter, insert-before or fold-left similarly terrible (and there are many more, basically every function using a verb)? The function names are very common in functional languages, much more than in traditionally imperative languages.

**Comment by ChristianGruen** [comment]
What about the suggestion to have a single `subsequence-where` function that combines `subsequence-starting-where` and `items-before` (or its negated version)?

```xquery
(: either start or before is optional :)
subsequence-where(
  ('A', 'B1', 'B2', 'C'),
  start := fn { . >= 'B' },
  before := fn { . = 'C' }
)
```

I agree that there will be more use cases for `subsequence-starting-where` than for `items-after`. Similarly, I assume that `items-before` will be used more often than `subsequence-ending-where`, so I think that two function parameters are enough. For the remaining cases, `fn:tail` and `fn:trunk` can be used.

**Comment by michaelhkay** [comment]
I'm thinking again about integrating the items-* quartet into a heavily overloaded `subsequence` function.

Must supply zero or one of:

- $start - the start position
- $from - a predicate, such that the start is the first item to match the predicate
- - defaulting to 1

And zero or one of:

- $length - the number of items to include
- $while - a predicate, the subsequence takes items so long as the predicate is true
- $until - a predicate, the subsequence takes items up to and including the first for which the predicate is false
- - defaulting to the end of the sequence.

This omits the "items-after" combination, but that one is easily achieved using `tail(subsequence(from:="xxx"))`.

**Comment by ChristianGruen** [comment]
> I'm thinking again about integrating the items-* quartet into a heavily overloaded `subsequence` function.

Looks sound. The only thing that frightens me is the semantics of the existing `fn:subsequence` function, which is already exciting and error-prone enough (accepting doubles, both positive and negative, as offsets, rounded to integers, etc.).

Personally, I would be happy to drop the 4 functions completely and adding some more examples to `fn:subsequence`. Instead of…

```xquery
let $fruits := ('apple', 'banana', 'cherry', 'durian')
return subsequence($fruits, from := fn { . = 'cherry' })
```

…we would have:

```xquery
let $fruits := ('apple', 'banana', 'cherry', 'durian')
let $start := head(index-of($fruits, 'cherry'))
return subsequence($fruits, $start)
```
