### ISSUE TITLE
$position argument in fold-right

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#864]
In fn:fold-right (and thus array:fold-right) it's not clear how the position parameter works.

It appears to start at 1, and then to be decremented, which seems a little weird.

Working out what happens seems to involve reverse engineering the code, which isn't ideal. It's useful to have a formal definition of the function using code, but it shouldn't be necessary to reverse engineer 20 lines of difficult recursive code in order to get a feel for what the function does.

The only example given doesn't add any clarification.

**Comment by ChristianGruen** [comment]
> It appears to start at 1, and then to be decremented, which seems a little weird.

That's wrong indeed; the start value should be `count($input)`. Starting at 1 and incrementing would be a reasonable alternative; I’m open to discussing this.

> Working out what happens seems to involve reverse engineering the code, which isn't ideal. It's useful to have a formal definition of the function using code, but it shouldn't be necessary to reverse engineer 20 lines of difficult recursive code in order to get a feel for what the function does.

I certainly wouldn’t mind if the documentation was revised. Maybe version 3.1 was already flawed (I simply added the position argument to that version):

https://www.w3.org/TR/xpath-functions-31/#func-fold-right

The rule sets of various other functions in the spec seem to be limited to an equivalent implementation/expression. Are there rules one can follow when an informal section is required?

**Comment by michaelhkay** [comment]
I think array:flatten is a better example of good practice: a couple of paragraphs of informal prose saying what the function does; a formal definition in terms of a code sample; and sufficient examples to illustrate the behaviour for readers who prefer to learn from examples; ideally examples that are motivating as well as explanatory.

For fn:fold-left and fn:fold-right the informal explanation appears under "Notes" rather than "Rules", which is OK, but for array:fold-left and array:fold-right it is missing entirely. This only really becomes noticeable with the new position argument where there is nothing other than the recursive code to help you understand how it works.

A simple statement that the value of the position argument corresponds to the position of the item in the input sequence (and not, therefore, to the order in which items are processed) would be helpful.

**Comment by ChristianGruen** [comment]
I’ve incorporated your suggestions in an existing PR (#851): https://github.com/qt4cg/qtspecs/pull/851/commits/709ceda64b6166ba41922ada0b9cb8b7d7b96742.

Maybe the existing notes for the fold functions could be revised as well (or rewritten to informal rules?). In particular, I simply don’t manage to grasp what this sentence is supposed to mean (as so often, it may also be due to my poor command of the English language):

> […] The accumulated result is initially set to the value of the $zero argument, which is conventionally a value […] that causes the function to return the value of the other argument unchanged.

I remember that (even as an implementor) I never tried to understand the existing text in the XQFO specification for these particular functions. Instead, I checked how folds work in other languages. The documentation of JavaScript for [Array.reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) could be helpful if we believe that we want to make folds accessible to ordinary mortals.
