### ISSUE TITLE
[XSL] Support for "master files"

### ISSUE THREAD

**Issue by mricaud** [qt4cg/qtspecs#87]
Oxygen allows to set one or more "master files" on a project. This is quite usefull when validating or searching for references while editing XSLT "modules" that depends on a main XSLT.

The main use-case is when I have an big XSLT that I want to split into modules (typically on module per mode). I could off course gather each global variable / parameters / function into the same module, but then I have to import it from each module if I want every XSLT to be valid. It would make more sens to import it once from the main XSLT, but then none of the other modules are valid anymore. 

Being able to set master files would help in validation as a common XSLT feature. It would have no incidence on compilation but only as validation feature.

What do you think ?

**Comment by michaelhkay** [comment]
I think that XSLT 3.0 packages meet most of this requirement.

If there are requirements beyond that, I'd like to see a concrete proposal with syntax and semantics fleshed out.

**Comment by michaelhkay** [comment]
I would suggest an optional attribute `main-module="href"` on `xsl:stylesheet` documented as follows.

This attribute is purely documentary and has no effect on the semantics of the stylesheet. Where a stylesheet module is intended to be used as part of a larger package, this attribute may be used to identify the principal stylesheet module of the package. The attribute might be used, for example, by syntax-aware editing tools: when a module is opened for editing, the editor may be able to use the attribute to locate the principal stylesheet module of the package and thus to  identify all components (such as named templates, global variables, and functions) that are available for use in the module being edited, and offer these as candidates for code completion and early semantic checking.

The presence of the attribute does not prevent the module being used as part of some other package. An XSLT processor must not signal an error if the URI is absent or malformed or if it cannot be resolved.

**Comment by pgfearo** [comment]
1. Is there really a need to *explicitly* identify a master/main XSLT module for the XSLT editor?

The Visual Studio Code editor *infers* the 'master module' for the current stylesheet module. It does this by checking if the current module matches any direct/indirect imports found in any stylesheet modules previously visited by the user. 

This is not perfect, but, so long as the user has already visited the master module in the same session (and there are no redundant imports in child modules), all references to symbols declared outside the current module can be resolved for the purpose of validation etc.

2. Would this be the first case of a purely documentary attribute in the XSLT specification?
3. If we are going to have purely documentary information in XSLT, could we not use a processing instruction in the XML prolog instead (to help distinguish it)?

**Comment by michaelhkay** [comment]
I can imagine that the "previously visited" criterion might cause rather unpredictable behaviour? One day you're prompted for all the functions you can call, the next day those functions are flagged as errors...

I don't think there's any problem with stuff that's purely documentary. That currently applies, for example, to "data elements" - unrecognised children of xsl:transform - and we're proposing adding a new xsl:note as well.

I don't find the idea of using a processing instruction particularly appealing.

**Comment by ndw** [comment]
For completely general associations (this stylesheet or this schema with this XML document, where the expectation is that it can apply to *any* XML vocabulary), it makes sense to use a PI. We're defining an XSL thing for an XSL stylesheet. Putting it in the XSL vocabulary proper (as an attribute, for example) makes a lot more sense, I think.

**Comment by pgfearo** [comment]
@michaelhkay 

Regarding:

> I can imagine that the "previously visited" criterion might cause rather unpredictable behaviour? One day you're prompted for all the functions you can call, the next day those functions are flagged as errors..

I rely on issues submitted by users on GitHub to let me know if they have problems with particular features. No one has flagged this as a problem yet. 

I exploit this feature almost daily myself, normally without a second thought. But I can't claim to be a typical XSLT user. Rather than navigating directly to a 'non-standalone' XSLT stylesheet module, I tend to arrive at it via a `CMD-Click' or 'Goto-Definition/Reference' from the master module.

If on occasion I do spot the 'red-squiggly' lines indicating unresolved references in a stylesheet module then I know what I need to do to fix that (visit the nearest suitable importing module and then revert back to the target module).

If support for 'master files' is deemed popular and is likely to be supported by the Oxygen team and others then I will of course endeavour to include this for the significantly fewer number of regular VS Code XSLT users. 

The rather haphazard import hierarchy of the modules in the XSLT function library I use most of the time will not immediately benefit from a 'master file'. However, this feature may at least encourage us to create 'virtual' modules whose single purpose is to group child modules that have interdependencies.

**Comment by pgfearo** [comment]
Incidentally, a VS Code user raised a [StackOverFlow question](https://stackoverflow.com/q/74401292/63965) related to this issue yesterday. The nature of this question implies that the 'visit the main module first' approach currently required by VS Code is non-obvious.

**Comment by mricaud** [comment]
Thanks for taking this into account, I'm sorry I didn't find time to follow the discussion, but this main-module attribute is quite a good solution. I guess one can add only one value ? Oxygen allow multiple master files at project level, but as long as I can imagine, one master file per stylesheet sounds quite enough.
