### ISSUE TITLE
Support order by ascending/descending from a string value.

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#93]
### Use Case
It is a common pattern to have a sort key and direction on requests that support listing or searching an object (e.g. authors).

Currently, in order to switch between ascending/descending in a FLWOR expression two separate expressions need to be written. For example:

    if ($sort-order eq "ascending") then
        for $name in $authors order by $name ascending return $name
    else
        for $name in $authors order by $name descending return $name

It would be cleaner if this could be rewritten as:

    for $name in $authors
    order by $name in $sort-order order
    return $name

### Syntax
    OrderModifier ::= ("ascending"  |  "descending"  |  OrderDirection)?
                      ("empty"  ("greatest"  |  "least"))?
                      ("collation" URILiteral)?
    OrderDirection ::= "in" ExprSingle "order"

### Semantics
If OrderDirection is used, the expression is evaluated.
1. If the expression is not a single atomic value, an XQST#### error is raised.
2. If the expression evaluates to the string "ascending", this is the same as using the `ascending` keyword.
3. If the expression evaluates to the string "descending", this is the same as using the `descending` keyword.
4. Otherwise, an XQST#### error is raised.

**Comment by ChristianGruen** [comment]
I like this idea in general. I wonder, though, how the following expression would be evaluated?

```xquery
for $a in ('ascending', 'descending')
order by $a in $a order
return $a
```

**Comment by rhdunn** [comment]
I would constrain it to dynamic context that does not change over the course of the loop -- i.e. I would expect that expression to be an error. However, something like:

    for $a in ("ascending", "descending")
    for $b in $items
    order by $b in $a order
    return $b

should be valid, as it is constant across the evaluation of the `$b` sequence. However, I'm happy for that to also be an error if it makes the constant in-order check easier, as you can always add a return between the two for clauses to create two flwor expressions.

**Comment by michaelhkay** [comment]
My problem with this proposal is that the order direction is by no means the only thing in the order by clause that has to be specified statically. The same is true of the collation, the "empty least" clause, etc etc.

Indeed, in an interactive application, users expect to be able to sort a table on any column, in which case the choice of sort key itself is dynamic.

I think the right approach for more dynamic sorting should be using a function. We do now have fn:sort(), though unfortunately it lacks the ability to handle multiple sort keys, or any kind of ascending/descending control. 

One solution to more powerful sorting would a variant of fn:sort that uses a comparator function. We've resisted this in the past because we can't trust a user-supplied comparator function to be well behaved (e.g. transitive). I wonder how serious an obstacle this is?

**Comment by ChristianGruen** [comment]
👍🏻 for a sort function with a comparator argument

**Comment by michaelhkay** [comment]
I would suggest enhancing fn:sort: define an optional argument `$sort-keys` (as an alternative to `$key + $collation`) whose value is a sequence of records, one describing each sort key in major-to-minor order. The fields in each record are:

```
key: function(item()) as xs:anyAtomicType* -- computes the sort key value. Required.
ascending: boolean, true for ascending, false for descending. Defaults to true.
collation: string, the collation to be used when comparing strings. Defaults to default-collation().
```

Specifying `sort($input, $collation, $key)` becomes a shorthand for `sort($input, sort-keys:=map{"key":$key, "collation":$collation})`

I don't propose adding "empty least/greatest" from XQuery `order by` - the effect can easily be achieved by adding another sort key. And I don't propose adding options from xsl:sort such as case-order and language; these can be achieved by choosing an appropriate collation.

I would leave XQuery "order by" alone, because enhancing it with similar capabilities is too complex. That's partly because it's sorting a tuple stream rather than an XDM value, and partly because making the details of the sorting options dynamic creates problems with the scope of variables.

Example: 

`sort($input, sort-keys:=(map{"key":fn{last-name}}, map{"key":fn{date-joined}, "ascending":false()}))`

**Comment by ChristianGruen** [comment]
I’ve added some comments to the latest proposal: https://github.com/qt4cg/qtspecs/pull/623#issuecomment-1670781368
