### ISSUE TITLE
Milliseconds ↔ xs:dayTimeDuration, Unix time ↔ xs:dateTime

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#959]
We should extend the constructor functions to convert integers (millisecond, and the Unix time, starting from `1970-01-01T00:00:00Z`) to `xs:dayTimeDuration` and `xs:dateTime` instances…

```xquery
xs:dateTime(12345),
xs:dayTimeDuration(12345)
```

…and it should be possible to convert the values back to integers.

Related: https://docs.basex.org/wiki/Conversion_Module#Dates_and_Durations

**Comment by michaelhkay** [comment]
While conversion to/from Unix dates and times might be very handy for many users, it's not the only way of representing a date/time as an integer, so I think it should be a much more specific function saying exactly what it does, rather than an overload of the constructor.

If the reason for manipulating the value as a number is for ease of doing calculations, then Julian dates are surely more useful outside the field of Unix computing: they have a higher range and a higher precision.

**Comment by ChristianGruen** [comment]
That’s helpful, thanks. My proposal was mostly driven by user feedback, but I agree it would be reasonable to strive for a more generic approach.

**Comment by ChristianGruen** [comment]
Now that we have `fn:seconds`, should we also add `fn:unix-time`? Copied from https://github.com/qt4cg/qtspecs/pull/984#pullrequestreview-1853646986:

> […] we should add an alternative solution for `xs:dateTime('1970-01-01T00:00:00Z')`. It’s particularly tricky because of the timestamp syntax, and people may be tempted to write things like…
>
>```xquery
>xs:dateTime('1970-01-01T00:00:00') + seconds( (: input from 'date +%s' or similar :) )
>```
>
>…which gives a similar, but wrong result. `fn:unix-time()` would be my favorite (it seems more common to me than 'epoch', but I may be biased).

**Comment by ndw** [comment]
Why does that last example give incorrect results? Because "Z" is misisng?

**Comment by ChristianGruen** [comment]
> Why does that last example give incorrect results? Because "Z" is missing?

…right. `xs:date('1970-01-01') + seconds(...)` could be another failed attempt, caused by the complexity of date/time handling.
