### ISSUE TITLE
regular expression addition - comments

### ISSUE THREAD

**Issue by liamquin** [qt4cg/qtspecs#999]
The original Perl regular expression syntax allows comments with the x flag. They use # to introduce comments up to a newline.

Maybe we could support XPath-style comments in regular expressions, such as `(:#.......#:)` when the x flag is present?

Today i use `(?:comment: stuff here )?` but this requires that "stuff here" can be compiled into a regular expression!

**Comment by Arithmeticus** [comment]
This reminds me that I have sometimes wished that we had named groups, which serves a kind of commentary function. But the angle brackets used in C# regexes wouldn't be copacetic, and the colons might be just the right substitute. XSLT's `regex-group` could then be adjusted to allow integers or strings.

At any rate, comments and named groups would make regular expressions more declarative, and therefore more QT-like.

**Comment by liamquin** [comment]
Thanks, it’s possible named captures could be made available through a map. Perl uses $+{name} to refer to them in the substitution part, and also offers (?'NAME'pattern) which might work.

A thing to watch for with named groups is that in some systems (e.g. .NET) the named groups are not included in the numbering, and in others (including Perl) they are.

We can't use Perl's syntax for comments, because it's line based, and newlines in select attributes go away under attribute value normalization during parsing (or become spaces).

**Comment by michaelhkay** [comment]
The Perl syntax for comments ('#' up to newline) is clearly troublesome given XML attribute value normalization which kills newlines.

Coming up with any other syntax is difficult because anything we do might clash with some existing convention or prevent us adopting some regex feature that we're not currently aware of. 

Perhaps we could do something along the lines of "literate regular expressions" - see https://hackaday.com/2020/09/11/linux-fu-literate-regular-expressions/

Or just encourage people towards invisible XML.

**Comment by michaelhkay** [comment]
I suggest that we allow comments if the flag '#' is present, and that comments start with '#' and end with '#' or the end of the regex string. I don't think we can overload flag `x` to allow both comments and whitespace for backwards compatibility reasons. A '#' can be escaped by writing `\#` or `[#]`.

I'd suggest treating named capturing groups as a separate issue.
